2020-02-08 01:17:22,994 DEBUG download_runner.impl.historical_end_reader:37 poll stock ? => True
2020-02-08 01:17:23,124 ERROR root:30 unhandled exception getting latest timestamp for A
Traceback (most recent call last):
  File "/Users/dali/workspace/ib_python/runner/services/historical_data_service.py", line 24, in get_latest_timestamp
    response = self.stub.GetLatestTimeStamp(request)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 604, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 506, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1581124643.124684000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3876,"referenced_errors":[{"created":"@1581124643.124683000","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":395,"grpc_status":14}]}"
>
2020-02-08 01:17:23,126 INFO download_runner.impl.historical_runner:32 sending - historical data request : A 2010-01-01 2020-01-01
2020-02-08 01:17:27,378 INFO download_runner.impl.historical_runner:35 sent - historical data request : A 2010-01-01 2020-01-01
2020-02-08 01:17:27,378 DEBUG download_runner.impl.historical_runner:36 request accounted for...
2020-02-08 01:17:27,378 INFO download_runner.impl.historical_runner:37 status : True
2020-02-08 01:17:27,378 INFO download_runner.impl.historical_runner:42 Historical data request sent : A 2010-01-01 2020-01-01
2020-02-08 01:17:27,378 DEBUG download_runner.impl.historical_end_reader:37 poll stock ? => True
2020-02-08 01:17:27,378 ERROR root:30 unhandled exception getting latest timestamp for ACIA
Traceback (most recent call last):
  File "/Users/dali/workspace/ib_python/runner/services/historical_data_service.py", line 24, in get_latest_timestamp
    response = self.stub.GetLatestTimeStamp(request)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 604, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 506, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1581124647.378715000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3876,"referenced_errors":[{"created":"@1581124647.378713000","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":395,"grpc_status":14}]}"
>
2020-02-08 01:17:27,379 INFO download_runner.impl.historical_runner:32 sending - historical data request : ACIA 2010-01-01 2020-01-01
2020-02-08 01:17:28,843 INFO download_runner.impl.historical_runner:35 sent - historical data request : ACIA 2010-01-01 2020-01-01
2020-02-08 01:17:28,843 DEBUG download_runner.impl.historical_runner:36 request accounted for...
2020-02-08 01:17:28,843 INFO download_runner.impl.historical_runner:37 status : True
2020-02-08 01:17:28,843 INFO download_runner.impl.historical_runner:42 Historical data request sent : ACIA 2010-01-01 2020-01-01
2020-02-08 01:17:28,843 DEBUG download_runner.impl.historical_end_reader:37 poll stock ? => True
2020-02-08 01:17:28,843 ERROR root:30 unhandled exception getting latest timestamp for ACIO
Traceback (most recent call last):
  File "/Users/dali/workspace/ib_python/runner/services/historical_data_service.py", line 24, in get_latest_timestamp
    response = self.stub.GetLatestTimeStamp(request)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 604, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 506, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1581124648.843790000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3876,"referenced_errors":[{"created":"@1581124647.997948000","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":395,"grpc_status":14}]}"
>
2020-02-08 01:17:28,844 INFO download_runner.impl.historical_runner:32 sending - historical data request : ACIO 2010-01-01 2020-01-01
2020-02-08 01:17:29,329 INFO download_runner.impl.historical_runner:35 sent - historical data request : ACIO 2010-01-01 2020-01-01
2020-02-08 01:17:29,329 DEBUG download_runner.impl.historical_runner:36 request accounted for...
2020-02-08 01:17:29,330 INFO download_runner.impl.historical_runner:37 status : True
2020-02-08 01:17:29,330 INFO download_runner.impl.historical_runner:42 Historical data request sent : ACIO 2010-01-01 2020-01-01
2020-02-08 01:17:29,330 DEBUG download_runner.impl.historical_end_reader:37 poll stock ? => True
2020-02-08 01:17:29,330 ERROR root:30 unhandled exception getting latest timestamp for ACIU
Traceback (most recent call last):
  File "/Users/dali/workspace/ib_python/runner/services/historical_data_service.py", line 24, in get_latest_timestamp
    response = self.stub.GetLatestTimeStamp(request)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 604, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 506, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1581124649.330319000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3876,"referenced_errors":[{"created":"@1581124647.997948000","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":395,"grpc_status":14}]}"
>
2020-02-08 01:17:29,330 INFO download_runner.impl.historical_runner:32 sending - historical data request : ACIU 2010-01-01 2020-01-01
2020-02-08 01:17:30,889 INFO download_runner.impl.historical_runner:35 sent - historical data request : ACIU 2010-01-01 2020-01-01
2020-02-08 01:17:30,889 DEBUG download_runner.impl.historical_runner:36 request accounted for...
2020-02-08 01:17:30,889 INFO download_runner.impl.historical_runner:37 status : True
2020-02-08 01:17:30,889 INFO download_runner.impl.historical_runner:42 Historical data request sent : ACIU 2010-01-01 2020-01-01
2020-02-08 01:17:30,889 DEBUG download_runner.impl.historical_end_reader:37 poll stock ? => True
2020-02-08 01:17:30,889 ERROR root:30 unhandled exception getting latest timestamp for ACIW
Traceback (most recent call last):
  File "/Users/dali/workspace/ib_python/runner/services/historical_data_service.py", line 24, in get_latest_timestamp
    response = self.stub.GetLatestTimeStamp(request)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 604, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 506, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1581124650.889679000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3876,"referenced_errors":[{"created":"@1581124650.889677000","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":395,"grpc_status":14}]}"
>
2020-02-08 01:17:30,890 INFO download_runner.impl.historical_runner:32 sending - historical data request : ACIW 2010-01-01 2020-01-01
2020-02-08 01:17:39,070 INFO download_runner.impl.historical_runner:35 sent - historical data request : ACIW 2010-01-01 2020-01-01
2020-02-08 01:17:39,070 DEBUG download_runner.impl.historical_runner:36 request accounted for...
2020-02-08 01:17:39,070 INFO download_runner.impl.historical_runner:37 status : True
2020-02-08 01:17:39,070 INFO download_runner.impl.historical_runner:42 Historical data request sent : ACIW 2010-01-01 2020-01-01
2020-02-08 01:17:39,070 DEBUG download_runner.impl.historical_end_reader:37 poll stock ? => True
2020-02-08 01:17:39,071 ERROR root:30 unhandled exception getting latest timestamp for ACLS
Traceback (most recent call last):
  File "/Users/dali/workspace/ib_python/runner/services/historical_data_service.py", line 24, in get_latest_timestamp
    response = self.stub.GetLatestTimeStamp(request)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 604, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 506, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1581124659.071114000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3876,"referenced_errors":[{"created":"@1581124658.005874000","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":395,"grpc_status":14}]}"
>
2020-02-08 01:17:39,071 INFO download_runner.impl.historical_runner:32 sending - historical data request : ACLS 2010-01-01 2020-01-01
2020-02-08 01:17:46,193 INFO download_runner.impl.historical_runner:35 sent - historical data request : ACLS 2010-01-01 2020-01-01
2020-02-08 01:17:46,193 DEBUG download_runner.impl.historical_runner:36 request accounted for...
2020-02-08 01:17:46,193 INFO download_runner.impl.historical_runner:37 status : True
2020-02-08 01:17:46,193 INFO download_runner.impl.historical_runner:42 Historical data request sent : ACLS 2010-01-01 2020-01-01
2020-02-08 01:17:46,193 DEBUG download_runner.impl.historical_end_reader:37 poll stock ? => True
2020-02-08 01:17:46,194 ERROR root:30 unhandled exception getting latest timestamp for ACM
Traceback (most recent call last):
  File "/Users/dali/workspace/ib_python/runner/services/historical_data_service.py", line 24, in get_latest_timestamp
    response = self.stub.GetLatestTimeStamp(request)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 604, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 506, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1581124666.194194000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3876,"referenced_errors":[{"created":"@1581124663.006494000","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":395,"grpc_status":14}]}"
>
2020-02-08 01:17:46,194 INFO download_runner.impl.historical_runner:32 sending - historical data request : ACM 2010-01-01 2020-01-01
2020-02-08 01:17:57,593 INFO download_runner.impl.historical_runner:35 sent - historical data request : ACM 2010-01-01 2020-01-01
2020-02-08 01:17:57,594 DEBUG download_runner.impl.historical_runner:36 request accounted for...
2020-02-08 01:17:57,594 INFO download_runner.impl.historical_runner:37 status : True
2020-02-08 01:17:57,594 INFO download_runner.impl.historical_runner:42 Historical data request sent : ACM 2010-01-01 2020-01-01
2020-02-08 01:17:57,594 DEBUG download_runner.impl.historical_end_reader:37 poll stock ? => True
2020-02-08 01:17:57,595 ERROR root:30 unhandled exception getting latest timestamp for ACMR
Traceback (most recent call last):
  File "/Users/dali/workspace/ib_python/runner/services/historical_data_service.py", line 24, in get_latest_timestamp
    response = self.stub.GetLatestTimeStamp(request)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 604, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 506, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1581124677.595098000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3876,"referenced_errors":[{"created":"@1581124673.007055000","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":395,"grpc_status":14}]}"
>
2020-02-08 01:17:57,595 INFO download_runner.impl.historical_runner:32 sending - historical data request : ACMR 2010-01-01 2020-01-01
2020-02-08 01:18:00,433 INFO download_runner.impl.historical_runner:35 sent - historical data request : ACMR 2010-01-01 2020-01-01
2020-02-08 01:18:00,433 DEBUG download_runner.impl.historical_runner:36 request accounted for...
2020-02-08 01:18:00,433 INFO download_runner.impl.historical_runner:37 status : True
2020-02-08 01:18:00,433 INFO download_runner.impl.historical_runner:42 Historical data request sent : ACMR 2010-01-01 2020-01-01
2020-02-08 01:18:00,433 DEBUG download_runner.impl.historical_end_reader:37 poll stock ? => True
2020-02-08 01:18:00,434 ERROR root:30 unhandled exception getting latest timestamp for ACN
Traceback (most recent call last):
  File "/Users/dali/workspace/ib_python/runner/services/historical_data_service.py", line 24, in get_latest_timestamp
    response = self.stub.GetLatestTimeStamp(request)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 604, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 506, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1581124680.434194000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3876,"referenced_errors":[{"created":"@1581124673.007055000","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":395,"grpc_status":14}]}"
>
2020-02-08 01:18:00,434 INFO download_runner.impl.historical_runner:32 sending - historical data request : ACN 2010-01-01 2020-01-01
2020-02-08 01:18:27,126 INFO download_runner.impl.historical_runner:35 sent - historical data request : ACN 2010-01-01 2020-01-01
2020-02-08 01:18:27,126 DEBUG download_runner.impl.historical_runner:36 request accounted for...
2020-02-08 01:18:27,126 INFO download_runner.impl.historical_runner:37 status : True
2020-02-08 01:18:27,126 INFO download_runner.impl.historical_runner:42 Historical data request sent : ACN 2010-01-01 2020-01-01
2020-02-08 01:18:27,126 DEBUG download_runner.impl.historical_end_reader:37 poll stock ? => True
2020-02-08 01:18:27,126 ERROR root:30 unhandled exception getting latest timestamp for ACNB
Traceback (most recent call last):
  File "/Users/dali/workspace/ib_python/runner/services/historical_data_service.py", line 24, in get_latest_timestamp
    response = self.stub.GetLatestTimeStamp(request)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 604, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 506, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1581124707.126663000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3876,"referenced_errors":[{"created":"@1581124693.014367000","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":395,"grpc_status":14}]}"
>
2020-02-08 01:18:27,126 INFO download_runner.impl.historical_runner:32 sending - historical data request : ACNB 2010-01-01 2020-01-01
2020-02-08 01:18:27,958 INFO download_runner.impl.historical_runner:35 sent - historical data request : ACNB 2010-01-01 2020-01-01
2020-02-08 01:18:27,958 DEBUG download_runner.impl.historical_runner:36 request accounted for...
2020-02-08 01:18:27,958 INFO download_runner.impl.historical_runner:37 status : True
2020-02-08 01:18:27,958 INFO download_runner.impl.historical_runner:42 Historical data request sent : ACNB 2010-01-01 2020-01-01
2020-02-08 01:18:27,958 DEBUG download_runner.impl.historical_end_reader:37 poll stock ? => True
2020-02-08 01:18:27,959 ERROR root:30 unhandled exception getting latest timestamp for ACOR
Traceback (most recent call last):
  File "/Users/dali/workspace/ib_python/runner/services/historical_data_service.py", line 24, in get_latest_timestamp
    response = self.stub.GetLatestTimeStamp(request)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 604, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 506, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1581124707.959028000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3876,"referenced_errors":[{"created":"@1581124693.014367000","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":395,"grpc_status":14}]}"
>
2020-02-08 01:18:27,959 INFO download_runner.impl.historical_runner:32 sending - historical data request : ACOR 2010-01-01 2020-01-01
2020-02-08 01:18:33,051 INFO download_runner.impl.historical_runner:35 sent - historical data request : ACOR 2010-01-01 2020-01-01
2020-02-08 01:18:33,051 DEBUG download_runner.impl.historical_runner:36 request accounted for...
2020-02-08 01:18:33,051 INFO download_runner.impl.historical_runner:37 status : True
2020-02-08 01:18:33,051 INFO download_runner.impl.historical_runner:42 Historical data request sent : ACOR 2010-01-01 2020-01-01
2020-02-08 01:18:33,051 DEBUG download_runner.impl.historical_end_reader:37 poll stock ? => True
2020-02-08 01:18:33,051 ERROR root:30 unhandled exception getting latest timestamp for ACP
Traceback (most recent call last):
  File "/Users/dali/workspace/ib_python/runner/services/historical_data_service.py", line 24, in get_latest_timestamp
    response = self.stub.GetLatestTimeStamp(request)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 604, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 506, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1581124713.051698000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3876,"referenced_errors":[{"created":"@1581124693.014367000","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":395,"grpc_status":14}]}"
>
2020-02-08 01:18:33,052 INFO download_runner.impl.historical_runner:32 sending - historical data request : ACP 2010-01-01 2020-01-01
2020-02-08 01:18:38,573 INFO download_runner.impl.historical_runner:35 sent - historical data request : ACP 2010-01-01 2020-01-01
2020-02-08 01:18:38,573 DEBUG download_runner.impl.historical_runner:36 request accounted for...
2020-02-08 01:18:38,573 INFO download_runner.impl.historical_runner:37 status : True
2020-02-08 01:18:38,573 INFO download_runner.impl.historical_runner:42 Historical data request sent : ACP 2010-01-01 2020-01-01
2020-02-08 01:18:38,573 DEBUG download_runner.impl.historical_end_reader:37 poll stock ? => True
2020-02-08 01:18:38,573 ERROR root:30 unhandled exception getting latest timestamp for ACRE
Traceback (most recent call last):
  File "/Users/dali/workspace/ib_python/runner/services/historical_data_service.py", line 24, in get_latest_timestamp
    response = self.stub.GetLatestTimeStamp(request)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 604, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 506, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1581124718.573594000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3876,"referenced_errors":[{"created":"@1581124693.014367000","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":395,"grpc_status":14}]}"
>
2020-02-08 01:18:38,573 INFO download_runner.impl.historical_runner:32 sending - historical data request : ACRE 2010-01-01 2020-01-01
2020-02-08 01:18:43,986 INFO download_runner.impl.historical_runner:35 sent - historical data request : ACRE 2010-01-01 2020-01-01
2020-02-08 01:18:43,986 DEBUG download_runner.impl.historical_runner:36 request accounted for...
2020-02-08 01:18:43,986 INFO download_runner.impl.historical_runner:37 status : True
2020-02-08 01:18:43,986 INFO download_runner.impl.historical_runner:42 Historical data request sent : ACRE 2010-01-01 2020-01-01
2020-02-08 01:18:43,986 DEBUG download_runner.impl.historical_end_reader:37 poll stock ? => True
2020-02-08 01:18:43,987 ERROR root:30 unhandled exception getting latest timestamp for ACRS
Traceback (most recent call last):
  File "/Users/dali/workspace/ib_python/runner/services/historical_data_service.py", line 24, in get_latest_timestamp
    response = self.stub.GetLatestTimeStamp(request)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 604, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 506, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1581124723.987147000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3876,"referenced_errors":[{"created":"@1581124723.029510000","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":395,"grpc_status":14}]}"
>
2020-02-08 01:18:43,987 INFO download_runner.impl.historical_runner:32 sending - historical data request : ACRS 2010-01-01 2020-01-01
2020-02-08 01:18:45,757 INFO download_runner.impl.historical_runner:35 sent - historical data request : ACRS 2010-01-01 2020-01-01
2020-02-08 01:18:45,757 DEBUG download_runner.impl.historical_runner:36 request accounted for...
2020-02-08 01:18:45,757 INFO download_runner.impl.historical_runner:37 status : True
2020-02-08 01:18:45,757 INFO download_runner.impl.historical_runner:42 Historical data request sent : ACRS 2010-01-01 2020-01-01
2020-02-08 01:18:45,758 DEBUG download_runner.impl.historical_end_reader:37 poll stock ? => True
2020-02-08 01:18:45,758 ERROR root:30 unhandled exception getting latest timestamp for ACRX
Traceback (most recent call last):
  File "/Users/dali/workspace/ib_python/runner/services/historical_data_service.py", line 24, in get_latest_timestamp
    response = self.stub.GetLatestTimeStamp(request)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 604, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 506, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1581124725.758243000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3876,"referenced_errors":[{"created":"@1581124723.029510000","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":395,"grpc_status":14}]}"
>
2020-02-08 01:18:45,758 INFO download_runner.impl.historical_runner:32 sending - historical data request : ACRX 2010-01-01 2020-01-01
2020-02-08 01:19:02,795 INFO download_runner.impl.historical_runner:35 sent - historical data request : ACRX 2010-01-01 2020-01-01
2020-02-08 01:19:02,795 DEBUG download_runner.impl.historical_runner:36 request accounted for...
2020-02-08 01:19:02,795 INFO download_runner.impl.historical_runner:37 status : True
2020-02-08 01:19:02,795 INFO download_runner.impl.historical_runner:42 Historical data request sent : ACRX 2010-01-01 2020-01-01
2020-02-08 01:19:02,795 DEBUG download_runner.impl.historical_end_reader:37 poll stock ? => True
2020-02-08 01:19:02,796 ERROR root:30 unhandled exception getting latest timestamp for ACSG
Traceback (most recent call last):
  File "/Users/dali/workspace/ib_python/runner/services/historical_data_service.py", line 24, in get_latest_timestamp
    response = self.stub.GetLatestTimeStamp(request)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 604, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 506, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1581124742.795973000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3876,"referenced_errors":[{"created":"@1581124723.029510000","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":395,"grpc_status":14}]}"
>
2020-02-08 01:19:02,796 INFO download_runner.impl.historical_runner:32 sending - historical data request : ACSG 2010-01-01 2020-01-01
2020-02-08 01:19:05,913 INFO download_runner.impl.historical_runner:35 sent - historical data request : ACSG 2010-01-01 2020-01-01
2020-02-08 01:19:05,914 DEBUG download_runner.impl.historical_runner:36 request accounted for...
2020-02-08 01:19:05,914 INFO download_runner.impl.historical_runner:37 status : True
2020-02-08 01:19:05,914 INFO download_runner.impl.historical_runner:42 Historical data request sent : ACSG 2010-01-01 2020-01-01
2020-02-08 01:19:05,914 DEBUG download_runner.impl.historical_end_reader:37 poll stock ? => True
2020-02-08 01:19:05,914 ERROR root:30 unhandled exception getting latest timestamp for ACSI
Traceback (most recent call last):
  File "/Users/dali/workspace/ib_python/runner/services/historical_data_service.py", line 24, in get_latest_timestamp
    response = self.stub.GetLatestTimeStamp(request)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 604, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 506, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1581124745.914415000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3876,"referenced_errors":[{"created":"@1581124723.029510000","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":395,"grpc_status":14}]}"
>
2020-02-08 01:19:05,914 INFO download_runner.impl.historical_runner:32 sending - historical data request : ACSI 2010-01-01 2020-01-01
2020-02-08 01:19:24,914 INFO download_runner.impl.historical_runner:35 sent - historical data request : ACSI 2010-01-01 2020-01-01
2020-02-08 01:19:24,914 DEBUG download_runner.impl.historical_runner:36 request accounted for...
2020-02-08 01:19:24,914 INFO download_runner.impl.historical_runner:37 status : True
2020-02-08 01:19:24,914 INFO download_runner.impl.historical_runner:42 Historical data request sent : ACSI 2010-01-01 2020-01-01
2020-02-08 01:19:24,914 DEBUG download_runner.impl.historical_end_reader:37 poll stock ? => True
2020-02-08 01:19:24,914 ERROR root:30 unhandled exception getting latest timestamp for ACST
Traceback (most recent call last):
  File "/Users/dali/workspace/ib_python/runner/services/historical_data_service.py", line 24, in get_latest_timestamp
    response = self.stub.GetLatestTimeStamp(request)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 604, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 506, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1581124764.914901000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3876,"referenced_errors":[{"created":"@1581124723.029510000","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":395,"grpc_status":14}]}"
>
2020-02-08 01:19:24,915 INFO download_runner.impl.historical_runner:32 sending - historical data request : ACST 2010-01-01 2020-01-01
2020-02-08 01:19:27,773 INFO download_runner.impl.historical_runner:35 sent - historical data request : ACST 2010-01-01 2020-01-01
2020-02-08 01:19:27,774 DEBUG download_runner.impl.historical_runner:36 request accounted for...
2020-02-08 01:19:27,774 INFO download_runner.impl.historical_runner:37 status : True
2020-02-08 01:19:27,774 INFO download_runner.impl.historical_runner:42 Historical data request sent : ACST 2010-01-01 2020-01-01
2020-02-08 01:19:27,774 DEBUG download_runner.impl.historical_end_reader:37 poll stock ? => True
2020-02-08 01:19:27,774 ERROR root:30 unhandled exception getting latest timestamp for ACT
Traceback (most recent call last):
  File "/Users/dali/workspace/ib_python/runner/services/historical_data_service.py", line 24, in get_latest_timestamp
    response = self.stub.GetLatestTimeStamp(request)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 604, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 506, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1581124767.774695000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3876,"referenced_errors":[{"created":"@1581124723.029510000","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":395,"grpc_status":14}]}"
>
2020-02-08 01:19:27,775 INFO download_runner.impl.historical_runner:32 sending - historical data request : ACT 2010-01-01 2020-01-01
2020-02-08 01:19:28,848 INFO download_runner.impl.historical_runner:35 sent - historical data request : ACT 2010-01-01 2020-01-01
2020-02-08 01:19:28,848 DEBUG download_runner.impl.historical_runner:36 request accounted for...
2020-02-08 01:19:28,848 INFO download_runner.impl.historical_runner:37 status : True
2020-02-08 01:19:28,848 INFO download_runner.impl.historical_runner:42 Historical data request sent : ACT 2010-01-01 2020-01-01
2020-02-08 01:19:28,848 DEBUG download_runner.impl.historical_end_reader:37 poll stock ? => True
2020-02-08 01:19:28,849 ERROR root:30 unhandled exception getting latest timestamp for ACTG
Traceback (most recent call last):
  File "/Users/dali/workspace/ib_python/runner/services/historical_data_service.py", line 24, in get_latest_timestamp
    response = self.stub.GetLatestTimeStamp(request)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 604, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 506, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1581124768.849227000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3876,"referenced_errors":[{"created":"@1581124723.029510000","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":395,"grpc_status":14}]}"
>
2020-02-08 01:19:28,849 INFO download_runner.impl.historical_runner:32 sending - historical data request : ACTG 2010-01-01 2020-01-01
2020-02-08 01:19:33,024 INFO download_runner.impl.historical_runner:35 sent - historical data request : ACTG 2010-01-01 2020-01-01
2020-02-08 01:19:33,024 DEBUG download_runner.impl.historical_runner:36 request accounted for...
2020-02-08 01:19:33,024 INFO download_runner.impl.historical_runner:37 status : True
2020-02-08 01:19:33,024 INFO download_runner.impl.historical_runner:42 Historical data request sent : ACTG 2010-01-01 2020-01-01
2020-02-08 01:19:33,024 DEBUG download_runner.impl.historical_end_reader:37 poll stock ? => True
2020-02-08 01:19:33,025 ERROR root:30 unhandled exception getting latest timestamp for ACTT
Traceback (most recent call last):
  File "/Users/dali/workspace/ib_python/runner/services/historical_data_service.py", line 24, in get_latest_timestamp
    response = self.stub.GetLatestTimeStamp(request)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 604, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 506, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1581124773.025045000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3876,"referenced_errors":[{"created":"@1581124773.025043000","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":395,"grpc_status":14}]}"
>
2020-02-08 01:19:33,025 INFO download_runner.impl.historical_runner:32 sending - historical data request : ACTT 2010-01-01 2020-01-01
2020-02-08 01:19:33,625 INFO download_runner.impl.historical_runner:35 sent - historical data request : ACTT 2010-01-01 2020-01-01
2020-02-08 01:19:33,625 DEBUG download_runner.impl.historical_runner:36 request accounted for...
2020-02-08 01:19:33,625 INFO download_runner.impl.historical_runner:37 status : True
2020-02-08 01:19:33,625 INFO download_runner.impl.historical_runner:42 Historical data request sent : ACTT 2010-01-01 2020-01-01
2020-02-08 01:19:33,625 DEBUG download_runner.impl.historical_end_reader:37 poll stock ? => True
2020-02-08 01:19:33,625 ERROR root:30 unhandled exception getting latest timestamp for ACTTU
Traceback (most recent call last):
  File "/Users/dali/workspace/ib_python/runner/services/historical_data_service.py", line 24, in get_latest_timestamp
    response = self.stub.GetLatestTimeStamp(request)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 604, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 506, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1581124773.625902000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3876,"referenced_errors":[{"created":"@1581124773.025043000","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":395,"grpc_status":14}]}"
>
2020-02-08 01:19:33,626 INFO download_runner.impl.historical_runner:32 sending - historical data request : ACTTU 2010-01-01 2020-01-01
2020-02-08 01:19:34,220 INFO download_runner.impl.historical_runner:35 sent - historical data request : ACTTU 2010-01-01 2020-01-01
2020-02-08 01:19:34,220 DEBUG download_runner.impl.historical_runner:36 request accounted for...
2020-02-08 01:19:34,220 INFO download_runner.impl.historical_runner:37 status : True
2020-02-08 01:19:34,220 INFO download_runner.impl.historical_runner:42 Historical data request sent : ACTTU 2010-01-01 2020-01-01
2020-02-08 01:19:34,220 DEBUG download_runner.impl.historical_end_reader:37 poll stock ? => True
2020-02-08 01:19:34,220 ERROR root:30 unhandled exception getting latest timestamp for ACU
Traceback (most recent call last):
  File "/Users/dali/workspace/ib_python/runner/services/historical_data_service.py", line 24, in get_latest_timestamp
    response = self.stub.GetLatestTimeStamp(request)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 604, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 506, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1581124774.220606000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3876,"referenced_errors":[{"created":"@1581124773.025043000","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":395,"grpc_status":14}]}"
>
2020-02-08 01:19:34,220 INFO download_runner.impl.historical_runner:32 sending - historical data request : ACU 2010-01-01 2020-01-01
2020-02-08 01:19:46,750 INFO download_runner.impl.historical_runner:35 sent - historical data request : ACU 2010-01-01 2020-01-01
2020-02-08 01:19:46,750 DEBUG download_runner.impl.historical_runner:36 request accounted for...
2020-02-08 01:19:46,750 INFO download_runner.impl.historical_runner:37 status : True
2020-02-08 01:19:46,750 INFO download_runner.impl.historical_runner:42 Historical data request sent : ACU 2010-01-01 2020-01-01
2020-02-08 01:19:46,750 DEBUG download_runner.impl.historical_end_reader:37 poll stock ? => True
2020-02-08 01:19:46,751 ERROR root:30 unhandled exception getting latest timestamp for ACV
Traceback (most recent call last):
  File "/Users/dali/workspace/ib_python/runner/services/historical_data_service.py", line 24, in get_latest_timestamp
    response = self.stub.GetLatestTimeStamp(request)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 604, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 506, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1581124786.751103000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3876,"referenced_errors":[{"created":"@1581124773.025043000","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":395,"grpc_status":14}]}"
>
2020-02-08 01:19:46,751 INFO download_runner.impl.historical_runner:32 sending - historical data request : ACV 2010-01-01 2020-01-01
2020-02-08 01:19:49,662 INFO download_runner.impl.historical_runner:35 sent - historical data request : ACV 2010-01-01 2020-01-01
2020-02-08 01:19:49,663 DEBUG download_runner.impl.historical_runner:36 request accounted for...
2020-02-08 01:19:49,663 INFO download_runner.impl.historical_runner:37 status : True
2020-02-08 01:19:49,663 INFO download_runner.impl.historical_runner:42 Historical data request sent : ACV 2010-01-01 2020-01-01
2020-02-08 01:19:49,663 DEBUG download_runner.impl.historical_end_reader:37 poll stock ? => True
2020-02-08 01:19:49,663 ERROR root:30 unhandled exception getting latest timestamp for ACWF
Traceback (most recent call last):
  File "/Users/dali/workspace/ib_python/runner/services/historical_data_service.py", line 24, in get_latest_timestamp
    response = self.stub.GetLatestTimeStamp(request)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 604, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 506, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1581124789.663345000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3876,"referenced_errors":[{"created":"@1581124773.025043000","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":395,"grpc_status":14}]}"
>
2020-02-08 01:19:49,663 INFO download_runner.impl.historical_runner:32 sending - historical data request : ACWF 2010-01-01 2020-01-01
2020-02-08 01:19:52,867 INFO download_runner.impl.historical_runner:35 sent - historical data request : ACWF 2010-01-01 2020-01-01
2020-02-08 01:19:52,867 DEBUG download_runner.impl.historical_runner:36 request accounted for...
2020-02-08 01:19:52,867 INFO download_runner.impl.historical_runner:37 status : True
2020-02-08 01:19:52,867 INFO download_runner.impl.historical_runner:42 Historical data request sent : ACWF 2010-01-01 2020-01-01
2020-02-08 01:19:52,867 DEBUG download_runner.impl.historical_end_reader:37 poll stock ? => True
2020-02-08 01:19:52,868 ERROR root:30 unhandled exception getting latest timestamp for ACWI
Traceback (most recent call last):
  File "/Users/dali/workspace/ib_python/runner/services/historical_data_service.py", line 24, in get_latest_timestamp
    response = self.stub.GetLatestTimeStamp(request)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 604, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 506, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1581124792.868122000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3876,"referenced_errors":[{"created":"@1581124773.025043000","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":395,"grpc_status":14}]}"
>
2020-02-08 01:19:52,868 INFO download_runner.impl.historical_runner:32 sending - historical data request : ACWI 2010-01-01 2020-01-01
2020-02-08 01:20:05,396 INFO download_runner.impl.historical_runner:35 sent - historical data request : ACWI 2010-01-01 2020-01-01
2020-02-08 01:20:05,396 DEBUG download_runner.impl.historical_runner:36 request accounted for...
2020-02-08 01:20:05,397 INFO download_runner.impl.historical_runner:37 status : True
2020-02-08 01:20:05,397 INFO download_runner.impl.historical_runner:42 Historical data request sent : ACWI 2010-01-01 2020-01-01
2020-02-08 01:20:05,397 DEBUG download_runner.impl.historical_end_reader:37 poll stock ? => True
2020-02-08 01:20:05,397 ERROR root:30 unhandled exception getting latest timestamp for ACWV
Traceback (most recent call last):
  File "/Users/dali/workspace/ib_python/runner/services/historical_data_service.py", line 24, in get_latest_timestamp
    response = self.stub.GetLatestTimeStamp(request)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 604, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 506, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1581124805.397312000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3876,"referenced_errors":[{"created":"@1581124773.025043000","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":395,"grpc_status":14}]}"
>
2020-02-08 01:20:05,397 INFO download_runner.impl.historical_runner:32 sending - historical data request : ACWV 2010-01-01 2020-01-01
2020-02-08 01:20:28,641 INFO download_runner.impl.historical_runner:35 sent - historical data request : ACWV 2010-01-01 2020-01-01
2020-02-08 01:20:28,642 DEBUG download_runner.impl.historical_runner:36 request accounted for...
2020-02-08 01:20:28,642 INFO download_runner.impl.historical_runner:37 status : True
2020-02-08 01:20:28,642 INFO download_runner.impl.historical_runner:42 Historical data request sent : ACWV 2010-01-01 2020-01-01
2020-02-08 01:20:28,642 DEBUG download_runner.impl.historical_end_reader:37 poll stock ? => True
2020-02-08 01:20:28,642 ERROR root:30 unhandled exception getting latest timestamp for ACWX
Traceback (most recent call last):
  File "/Users/dali/workspace/ib_python/runner/services/historical_data_service.py", line 24, in get_latest_timestamp
    response = self.stub.GetLatestTimeStamp(request)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 604, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 506, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1581124828.642362000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3876,"referenced_errors":[{"created":"@1581124773.025043000","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":395,"grpc_status":14}]}"
>
2020-02-08 01:20:28,642 INFO download_runner.impl.historical_runner:32 sending - historical data request : ACWX 2010-01-01 2020-01-01
2020-02-08 01:20:35,586 INFO download_runner.impl.historical_runner:35 sent - historical data request : ACWX 2010-01-01 2020-01-01
2020-02-08 01:20:35,586 DEBUG download_runner.impl.historical_runner:36 request accounted for...
2020-02-08 01:20:35,586 INFO download_runner.impl.historical_runner:37 status : True
2020-02-08 01:20:35,586 INFO download_runner.impl.historical_runner:42 Historical data request sent : ACWX 2010-01-01 2020-01-01
2020-02-08 01:20:35,586 DEBUG download_runner.impl.historical_end_reader:37 poll stock ? => True
2020-02-08 01:20:35,586 ERROR root:30 unhandled exception getting latest timestamp for ACY
Traceback (most recent call last):
  File "/Users/dali/workspace/ib_python/runner/services/historical_data_service.py", line 24, in get_latest_timestamp
    response = self.stub.GetLatestTimeStamp(request)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 604, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 506, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1581124835.586440000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3876,"referenced_errors":[{"created":"@1581124833.080008000","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":395,"grpc_status":14}]}"
>
2020-02-08 01:20:35,586 INFO download_runner.impl.historical_runner:32 sending - historical data request : ACY 2010-01-01 2020-01-01
2020-02-08 01:20:42,542 INFO download_runner.impl.historical_runner:35 sent - historical data request : ACY 2010-01-01 2020-01-01
2020-02-08 01:20:42,543 DEBUG download_runner.impl.historical_runner:36 request accounted for...
2020-02-08 01:20:42,543 INFO download_runner.impl.historical_runner:37 status : True
2020-02-08 01:20:42,543 INFO download_runner.impl.historical_runner:42 Historical data request sent : ACY 2010-01-01 2020-01-01
2020-02-08 01:20:42,543 DEBUG download_runner.impl.historical_end_reader:37 poll stock ? => True
2020-02-08 01:20:42,543 ERROR root:30 unhandled exception getting latest timestamp for ADAP
Traceback (most recent call last):
  File "/Users/dali/workspace/ib_python/runner/services/historical_data_service.py", line 24, in get_latest_timestamp
    response = self.stub.GetLatestTimeStamp(request)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 604, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 506, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1581124842.543675000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3876,"referenced_errors":[{"created":"@1581124833.080008000","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":395,"grpc_status":14}]}"
>
2020-02-08 01:20:42,544 INFO download_runner.impl.historical_runner:32 sending - historical data request : ADAP 2010-01-01 2020-01-01
2020-02-08 01:20:45,994 INFO download_runner.impl.historical_runner:35 sent - historical data request : ADAP 2010-01-01 2020-01-01
2020-02-08 01:20:45,995 DEBUG download_runner.impl.historical_runner:36 request accounted for...
2020-02-08 01:20:45,995 INFO download_runner.impl.historical_runner:37 status : True
2020-02-08 01:20:45,995 INFO download_runner.impl.historical_runner:42 Historical data request sent : ADAP 2010-01-01 2020-01-01
2020-02-08 01:20:45,995 DEBUG download_runner.impl.historical_end_reader:37 poll stock ? => True
2020-02-08 01:20:45,995 ERROR root:30 unhandled exception getting latest timestamp for ADBE
Traceback (most recent call last):
  File "/Users/dali/workspace/ib_python/runner/services/historical_data_service.py", line 24, in get_latest_timestamp
    response = self.stub.GetLatestTimeStamp(request)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 604, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 506, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1581124845.995395000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3876,"referenced_errors":[{"created":"@1581124833.080008000","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":395,"grpc_status":14}]}"
>
2020-02-08 01:20:45,995 INFO download_runner.impl.historical_runner:32 sending - historical data request : ADBE 2010-01-01 2020-01-01
2020-02-08 01:20:51,623 INFO download_runner.impl.historical_runner:35 sent - historical data request : ADBE 2010-01-01 2020-01-01
2020-02-08 01:20:51,623 DEBUG download_runner.impl.historical_runner:36 request accounted for...
2020-02-08 01:20:51,623 INFO download_runner.impl.historical_runner:37 status : True
2020-02-08 01:20:51,623 INFO download_runner.impl.historical_runner:42 Historical data request sent : ADBE 2010-01-01 2020-01-01
2020-02-08 01:20:51,623 DEBUG download_runner.impl.historical_end_reader:37 poll stock ? => True
2020-02-08 01:20:51,624 ERROR root:30 unhandled exception getting latest timestamp for ADC
Traceback (most recent call last):
  File "/Users/dali/workspace/ib_python/runner/services/historical_data_service.py", line 24, in get_latest_timestamp
    response = self.stub.GetLatestTimeStamp(request)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 604, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 506, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1581124851.624049000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3876,"referenced_errors":[{"created":"@1581124833.080008000","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":395,"grpc_status":14}]}"
>
2020-02-08 01:20:51,624 INFO download_runner.impl.historical_runner:32 sending - historical data request : ADC 2010-01-01 2020-01-01
2020-02-08 01:20:57,745 INFO download_runner.impl.historical_runner:35 sent - historical data request : ADC 2010-01-01 2020-01-01
2020-02-08 01:20:57,745 DEBUG download_runner.impl.historical_runner:36 request accounted for...
2020-02-08 01:20:57,745 INFO download_runner.impl.historical_runner:37 status : True
2020-02-08 01:20:57,745 INFO download_runner.impl.historical_runner:42 Historical data request sent : ADC 2010-01-01 2020-01-01
2020-02-08 01:20:57,745 DEBUG download_runner.impl.historical_end_reader:37 poll stock ? => True
2020-02-08 01:20:57,745 ERROR root:30 unhandled exception getting latest timestamp for ADES
Traceback (most recent call last):
  File "/Users/dali/workspace/ib_python/runner/services/historical_data_service.py", line 24, in get_latest_timestamp
    response = self.stub.GetLatestTimeStamp(request)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 604, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 506, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1581124857.745649000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3876,"referenced_errors":[{"created":"@1581124833.080008000","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":395,"grpc_status":14}]}"
>
2020-02-08 01:20:57,745 INFO download_runner.impl.historical_runner:32 sending - historical data request : ADES 2010-01-01 2020-01-01
2020-02-08 01:20:59,781 INFO download_runner.impl.historical_runner:35 sent - historical data request : ADES 2010-01-01 2020-01-01
2020-02-08 01:20:59,781 DEBUG download_runner.impl.historical_runner:36 request accounted for...
2020-02-08 01:20:59,782 INFO download_runner.impl.historical_runner:37 status : True
2020-02-08 01:20:59,782 INFO download_runner.impl.historical_runner:42 Historical data request sent : ADES 2010-01-01 2020-01-01
2020-02-08 01:20:59,782 DEBUG download_runner.impl.historical_end_reader:37 poll stock ? => True
2020-02-08 01:20:59,782 ERROR root:30 unhandled exception getting latest timestamp for ADI
Traceback (most recent call last):
  File "/Users/dali/workspace/ib_python/runner/services/historical_data_service.py", line 24, in get_latest_timestamp
    response = self.stub.GetLatestTimeStamp(request)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 604, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 506, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1581124859.782314000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3876,"referenced_errors":[{"created":"@1581124833.080008000","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":395,"grpc_status":14}]}"
>
2020-02-08 01:20:59,782 INFO download_runner.impl.historical_runner:32 sending - historical data request : ADI 2010-01-01 2020-01-01
2020-02-08 01:21:27,642 INFO download_runner.impl.historical_runner:35 sent - historical data request : ADI 2010-01-01 2020-01-01
2020-02-08 01:21:27,642 DEBUG download_runner.impl.historical_runner:36 request accounted for...
2020-02-08 01:21:27,642 INFO download_runner.impl.historical_runner:37 status : True
2020-02-08 01:21:27,642 INFO download_runner.impl.historical_runner:42 Historical data request sent : ADI 2010-01-01 2020-01-01
2020-02-08 01:21:27,642 DEBUG download_runner.impl.historical_end_reader:37 poll stock ? => True
2020-02-08 01:21:27,642 ERROR root:30 unhandled exception getting latest timestamp for ADIL
Traceback (most recent call last):
  File "/Users/dali/workspace/ib_python/runner/services/historical_data_service.py", line 24, in get_latest_timestamp
    response = self.stub.GetLatestTimeStamp(request)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 604, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 506, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1581124887.642503000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3876,"referenced_errors":[{"created":"@1581124833.080008000","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":395,"grpc_status":14}]}"
>
2020-02-08 01:21:27,642 INFO download_runner.impl.historical_runner:32 sending - historical data request : ADIL 2010-01-01 2020-01-01
2020-02-08 01:21:28,801 INFO download_runner.impl.historical_runner:35 sent - historical data request : ADIL 2010-01-01 2020-01-01
2020-02-08 01:21:28,801 DEBUG download_runner.impl.historical_runner:36 request accounted for...
2020-02-08 01:21:28,801 INFO download_runner.impl.historical_runner:37 status : True
2020-02-08 01:21:28,801 INFO download_runner.impl.historical_runner:42 Historical data request sent : ADIL 2010-01-01 2020-01-01
2020-02-08 01:21:28,801 DEBUG download_runner.impl.historical_end_reader:37 poll stock ? => True
2020-02-08 01:21:28,801 ERROR root:30 unhandled exception getting latest timestamp for ADM
Traceback (most recent call last):
  File "/Users/dali/workspace/ib_python/runner/services/historical_data_service.py", line 24, in get_latest_timestamp
    response = self.stub.GetLatestTimeStamp(request)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 604, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 506, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1581124888.801857000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3876,"referenced_errors":[{"created":"@1581124833.080008000","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":395,"grpc_status":14}]}"
>
2020-02-08 01:21:28,802 INFO download_runner.impl.historical_runner:32 sending - historical data request : ADM 2010-01-01 2020-01-01
2020-02-08 01:21:34,587 INFO download_runner.impl.historical_runner:35 sent - historical data request : ADM 2010-01-01 2020-01-01
2020-02-08 01:21:34,587 DEBUG download_runner.impl.historical_runner:36 request accounted for...
2020-02-08 01:21:34,587 INFO download_runner.impl.historical_runner:37 status : True
2020-02-08 01:21:34,587 INFO download_runner.impl.historical_runner:42 Historical data request sent : ADM 2010-01-01 2020-01-01
2020-02-08 01:21:34,587 DEBUG download_runner.impl.historical_end_reader:37 poll stock ? => True
2020-02-08 01:21:34,588 ERROR root:30 unhandled exception getting latest timestamp for ADMA
Traceback (most recent call last):
  File "/Users/dali/workspace/ib_python/runner/services/historical_data_service.py", line 24, in get_latest_timestamp
    response = self.stub.GetLatestTimeStamp(request)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 604, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 506, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1581124894.588189000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3876,"referenced_errors":[{"created":"@1581124833.080008000","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":395,"grpc_status":14}]}"
>
2020-02-08 01:21:34,588 INFO download_runner.impl.historical_runner:32 sending - historical data request : ADMA 2010-01-01 2020-01-01
2020-02-08 01:21:35,179 INFO download_runner.impl.historical_runner:35 sent - historical data request : ADMA 2010-01-01 2020-01-01
2020-02-08 01:21:35,179 DEBUG download_runner.impl.historical_runner:36 request accounted for...
2020-02-08 01:21:35,179 INFO download_runner.impl.historical_runner:37 status : True
2020-02-08 01:21:35,179 INFO download_runner.impl.historical_runner:42 Historical data request sent : ADMA 2010-01-01 2020-01-01
2020-02-08 01:21:35,179 DEBUG download_runner.impl.historical_end_reader:37 poll stock ? => True
2020-02-08 01:21:35,179 ERROR root:30 unhandled exception getting latest timestamp for ADME
Traceback (most recent call last):
  File "/Users/dali/workspace/ib_python/runner/services/historical_data_service.py", line 24, in get_latest_timestamp
    response = self.stub.GetLatestTimeStamp(request)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 604, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 506, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1581124895.179412000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3876,"referenced_errors":[{"created":"@1581124833.080008000","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":395,"grpc_status":14}]}"
>
2020-02-08 01:21:35,179 INFO download_runner.impl.historical_runner:32 sending - historical data request : ADME 2010-01-01 2020-01-01
2020-02-08 01:21:37,784 INFO download_runner.impl.historical_runner:35 sent - historical data request : ADME 2010-01-01 2020-01-01
2020-02-08 01:21:37,785 DEBUG download_runner.impl.historical_runner:36 request accounted for...
2020-02-08 01:21:37,785 INFO download_runner.impl.historical_runner:37 status : True
2020-02-08 01:21:37,785 INFO download_runner.impl.historical_runner:42 Historical data request sent : ADME 2010-01-01 2020-01-01
2020-02-08 01:21:37,785 DEBUG download_runner.impl.historical_end_reader:37 poll stock ? => True
2020-02-08 01:21:37,785 ERROR root:30 unhandled exception getting latest timestamp for ADMP
Traceback (most recent call last):
  File "/Users/dali/workspace/ib_python/runner/services/historical_data_service.py", line 24, in get_latest_timestamp
    response = self.stub.GetLatestTimeStamp(request)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 604, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 506, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1581124897.785340000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3876,"referenced_errors":[{"created":"@1581124833.080008000","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":395,"grpc_status":14}]}"
>
2020-02-08 01:21:37,785 INFO download_runner.impl.historical_runner:32 sending - historical data request : ADMP 2010-01-01 2020-01-01
2020-02-08 01:21:41,453 INFO download_runner.impl.historical_runner:35 sent - historical data request : ADMP 2010-01-01 2020-01-01
2020-02-08 01:21:41,454 DEBUG download_runner.impl.historical_runner:36 request accounted for...
2020-02-08 01:21:41,454 INFO download_runner.impl.historical_runner:37 status : True
2020-02-08 01:21:41,454 INFO download_runner.impl.historical_runner:42 Historical data request sent : ADMP 2010-01-01 2020-01-01
2020-02-08 01:21:41,454 DEBUG download_runner.impl.historical_end_reader:37 poll stock ? => True
2020-02-08 01:21:41,454 ERROR root:30 unhandled exception getting latest timestamp for ADMS
Traceback (most recent call last):
  File "/Users/dali/workspace/ib_python/runner/services/historical_data_service.py", line 24, in get_latest_timestamp
    response = self.stub.GetLatestTimeStamp(request)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 604, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 506, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1581124901.454391000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3876,"referenced_errors":[{"created":"@1581124833.080008000","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":395,"grpc_status":14}]}"
>
2020-02-08 01:21:41,454 INFO download_runner.impl.historical_runner:32 sending - historical data request : ADMS 2010-01-01 2020-01-01
2020-02-08 01:21:44,375 INFO download_runner.impl.historical_runner:35 sent - historical data request : ADMS 2010-01-01 2020-01-01
2020-02-08 01:21:44,375 DEBUG download_runner.impl.historical_runner:36 request accounted for...
2020-02-08 01:21:44,375 INFO download_runner.impl.historical_runner:37 status : True
2020-02-08 01:21:44,375 INFO download_runner.impl.historical_runner:42 Historical data request sent : ADMS 2010-01-01 2020-01-01
2020-02-08 01:21:44,375 DEBUG download_runner.impl.historical_end_reader:37 poll stock ? => True
2020-02-08 01:21:44,375 ERROR root:30 unhandled exception getting latest timestamp for ADNT
Traceback (most recent call last):
  File "/Users/dali/workspace/ib_python/runner/services/historical_data_service.py", line 24, in get_latest_timestamp
    response = self.stub.GetLatestTimeStamp(request)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 604, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 506, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1581124904.375448000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3876,"referenced_errors":[{"created":"@1581124833.080008000","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":395,"grpc_status":14}]}"
>
2020-02-08 01:21:44,375 INFO download_runner.impl.historical_runner:32 sending - historical data request : ADNT 2010-01-01 2020-01-01
2020-02-08 01:22:06,850 INFO download_runner.impl.historical_runner:35 sent - historical data request : ADNT 2010-01-01 2020-01-01
2020-02-08 01:22:06,850 DEBUG download_runner.impl.historical_runner:36 request accounted for...
2020-02-08 01:22:06,850 INFO download_runner.impl.historical_runner:37 status : True
2020-02-08 01:22:06,850 INFO download_runner.impl.historical_runner:42 Historical data request sent : ADNT 2010-01-01 2020-01-01
2020-02-08 01:22:06,850 DEBUG download_runner.impl.historical_end_reader:37 poll stock ? => True
2020-02-08 01:22:06,851 ERROR root:30 unhandled exception getting latest timestamp for ADP
Traceback (most recent call last):
  File "/Users/dali/workspace/ib_python/runner/services/historical_data_service.py", line 24, in get_latest_timestamp
    response = self.stub.GetLatestTimeStamp(request)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 604, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 506, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1581124926.851276000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3876,"referenced_errors":[{"created":"@1581124926.851274000","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":395,"grpc_status":14}]}"
>
2020-02-08 01:22:06,851 INFO download_runner.impl.historical_runner:32 sending - historical data request : ADP 2010-01-01 2020-01-01
2020-02-08 01:22:28,305 INFO download_runner.impl.historical_runner:35 sent - historical data request : ADP 2010-01-01 2020-01-01
2020-02-08 01:22:28,305 DEBUG download_runner.impl.historical_runner:36 request accounted for...
2020-02-08 01:22:28,305 INFO download_runner.impl.historical_runner:37 status : True
2020-02-08 01:22:28,305 INFO download_runner.impl.historical_runner:42 Historical data request sent : ADP 2010-01-01 2020-01-01
2020-02-08 01:22:28,305 DEBUG download_runner.impl.historical_end_reader:37 poll stock ? => True
2020-02-08 01:22:28,306 ERROR root:30 unhandled exception getting latest timestamp for ADPT
Traceback (most recent call last):
  File "/Users/dali/workspace/ib_python/runner/services/historical_data_service.py", line 24, in get_latest_timestamp
    response = self.stub.GetLatestTimeStamp(request)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 604, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 506, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1581124948.306049000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3876,"referenced_errors":[{"created":"@1581124926.851274000","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":395,"grpc_status":14}]}"
>
2020-02-08 01:22:28,306 INFO download_runner.impl.historical_runner:32 sending - historical data request : ADPT 2010-01-01 2020-01-01
2020-02-08 01:22:28,829 INFO download_runner.impl.historical_runner:35 sent - historical data request : ADPT 2010-01-01 2020-01-01
2020-02-08 01:22:28,829 DEBUG download_runner.impl.historical_runner:36 request accounted for...
2020-02-08 01:22:28,829 INFO download_runner.impl.historical_runner:37 status : True
2020-02-08 01:22:28,829 INFO download_runner.impl.historical_runner:42 Historical data request sent : ADPT 2010-01-01 2020-01-01
2020-02-08 01:22:28,829 DEBUG download_runner.impl.historical_end_reader:37 poll stock ? => True
2020-02-08 01:22:28,830 ERROR root:30 unhandled exception getting latest timestamp for ADRA
Traceback (most recent call last):
  File "/Users/dali/workspace/ib_python/runner/services/historical_data_service.py", line 24, in get_latest_timestamp
    response = self.stub.GetLatestTimeStamp(request)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 604, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 506, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1581124948.830031000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3876,"referenced_errors":[{"created":"@1581124926.851274000","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":395,"grpc_status":14}]}"
>
2020-02-08 01:22:28,830 INFO download_runner.impl.historical_runner:32 sending - historical data request : ADRA 2010-01-01 2020-01-01
2020-02-08 01:22:30,201 INFO download_runner.impl.historical_runner:35 sent - historical data request : ADRA 2010-01-01 2020-01-01
2020-02-08 01:22:30,201 DEBUG download_runner.impl.historical_runner:36 request accounted for...
2020-02-08 01:22:30,201 INFO download_runner.impl.historical_runner:37 status : True
2020-02-08 01:22:30,201 INFO download_runner.impl.historical_runner:42 Historical data request sent : ADRA 2010-01-01 2020-01-01
2020-02-08 01:22:30,201 DEBUG download_runner.impl.historical_end_reader:37 poll stock ? => True
2020-02-08 01:22:30,201 ERROR root:30 unhandled exception getting latest timestamp for ADRD
Traceback (most recent call last):
  File "/Users/dali/workspace/ib_python/runner/services/historical_data_service.py", line 24, in get_latest_timestamp
    response = self.stub.GetLatestTimeStamp(request)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 604, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 506, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1581124950.201533000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3876,"referenced_errors":[{"created":"@1581124926.851274000","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":395,"grpc_status":14}]}"
>
2020-02-08 01:22:30,201 INFO download_runner.impl.historical_runner:32 sending - historical data request : ADRD 2010-01-01 2020-01-01
2020-02-08 01:22:34,934 INFO download_runner.impl.historical_runner:35 sent - historical data request : ADRD 2010-01-01 2020-01-01
2020-02-08 01:22:34,934 DEBUG download_runner.impl.historical_runner:36 request accounted for...
2020-02-08 01:22:34,934 INFO download_runner.impl.historical_runner:37 status : True
2020-02-08 01:22:34,934 INFO download_runner.impl.historical_runner:42 Historical data request sent : ADRD 2010-01-01 2020-01-01
2020-02-08 01:22:34,934 DEBUG download_runner.impl.historical_end_reader:37 poll stock ? => True
2020-02-08 01:22:34,934 ERROR root:30 unhandled exception getting latest timestamp for ADRE
Traceback (most recent call last):
  File "/Users/dali/workspace/ib_python/runner/services/historical_data_service.py", line 24, in get_latest_timestamp
    response = self.stub.GetLatestTimeStamp(request)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 604, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 506, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1581124954.934647000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3876,"referenced_errors":[{"created":"@1581124926.851274000","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":395,"grpc_status":14}]}"
>
2020-02-08 01:22:34,934 INFO download_runner.impl.historical_runner:32 sending - historical data request : ADRE 2010-01-01 2020-01-01
2020-02-08 01:22:40,238 INFO download_runner.impl.historical_runner:35 sent - historical data request : ADRE 2010-01-01 2020-01-01
2020-02-08 01:22:40,238 DEBUG download_runner.impl.historical_runner:36 request accounted for...
2020-02-08 01:22:40,238 INFO download_runner.impl.historical_runner:37 status : True
2020-02-08 01:22:40,238 INFO download_runner.impl.historical_runner:42 Historical data request sent : ADRE 2010-01-01 2020-01-01
2020-02-08 01:22:40,238 DEBUG download_runner.impl.historical_end_reader:37 poll stock ? => True
2020-02-08 01:22:40,238 ERROR root:30 unhandled exception getting latest timestamp for ADRO
Traceback (most recent call last):
  File "/Users/dali/workspace/ib_python/runner/services/historical_data_service.py", line 24, in get_latest_timestamp
    response = self.stub.GetLatestTimeStamp(request)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 604, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 506, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1581124960.238615000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3876,"referenced_errors":[{"created":"@1581124926.851274000","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":395,"grpc_status":14}]}"
>
2020-02-08 01:22:40,238 INFO download_runner.impl.historical_runner:32 sending - historical data request : ADRO 2010-01-01 2020-01-01
2020-02-08 01:22:42,656 INFO download_runner.impl.historical_runner:35 sent - historical data request : ADRO 2010-01-01 2020-01-01
2020-02-08 01:22:42,656 DEBUG download_runner.impl.historical_runner:36 request accounted for...
2020-02-08 01:22:42,656 INFO download_runner.impl.historical_runner:37 status : True
2020-02-08 01:22:42,656 INFO download_runner.impl.historical_runner:42 Historical data request sent : ADRO 2010-01-01 2020-01-01
2020-02-08 01:22:42,656 DEBUG download_runner.impl.historical_end_reader:37 poll stock ? => True
2020-02-08 01:22:42,656 ERROR root:30 unhandled exception getting latest timestamp for ADRU
Traceback (most recent call last):
  File "/Users/dali/workspace/ib_python/runner/services/historical_data_service.py", line 24, in get_latest_timestamp
    response = self.stub.GetLatestTimeStamp(request)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 604, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 506, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1581124962.656671000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3876,"referenced_errors":[{"created":"@1581124926.851274000","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":395,"grpc_status":14}]}"
>
2020-02-08 01:22:42,656 INFO download_runner.impl.historical_runner:32 sending - historical data request : ADRU 2010-01-01 2020-01-01
2020-02-08 01:22:51,283 INFO download_runner.impl.historical_runner:35 sent - historical data request : ADRU 2010-01-01 2020-01-01
2020-02-08 01:22:51,283 DEBUG download_runner.impl.historical_runner:36 request accounted for...
2020-02-08 01:22:51,284 INFO download_runner.impl.historical_runner:37 status : True
2020-02-08 01:22:51,284 INFO download_runner.impl.historical_runner:42 Historical data request sent : ADRU 2010-01-01 2020-01-01
2020-02-08 01:22:51,284 DEBUG download_runner.impl.historical_end_reader:37 poll stock ? => True
2020-02-08 01:22:51,284 ERROR root:30 unhandled exception getting latest timestamp for ADS
Traceback (most recent call last):
  File "/Users/dali/workspace/ib_python/runner/services/historical_data_service.py", line 24, in get_latest_timestamp
    response = self.stub.GetLatestTimeStamp(request)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 604, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 506, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1581124971.284283000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3876,"referenced_errors":[{"created":"@1581124926.851274000","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":395,"grpc_status":14}]}"
>
2020-02-08 01:22:51,284 INFO download_runner.impl.historical_runner:32 sending - historical data request : ADS 2010-01-01 2020-01-01
2020-02-08 01:23:09,625 INFO download_runner.impl.historical_runner:35 sent - historical data request : ADS 2010-01-01 2020-01-01
2020-02-08 01:23:09,625 DEBUG download_runner.impl.historical_runner:36 request accounted for...
2020-02-08 01:23:09,625 INFO download_runner.impl.historical_runner:37 status : True
2020-02-08 01:23:09,625 INFO download_runner.impl.historical_runner:42 Historical data request sent : ADS 2010-01-01 2020-01-01
2020-02-08 01:23:09,625 DEBUG download_runner.impl.historical_end_reader:37 poll stock ? => True
2020-02-08 01:23:09,625 ERROR root:30 unhandled exception getting latest timestamp for ADSK
Traceback (most recent call last):
  File "/Users/dali/workspace/ib_python/runner/services/historical_data_service.py", line 24, in get_latest_timestamp
    response = self.stub.GetLatestTimeStamp(request)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 604, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 506, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1581124989.625653000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3876,"referenced_errors":[{"created":"@1581124926.851274000","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":395,"grpc_status":14}]}"
>
2020-02-08 01:23:09,625 INFO download_runner.impl.historical_runner:32 sending - historical data request : ADSK 2010-01-01 2020-01-01
2020-02-08 01:23:27,440 INFO download_runner.impl.historical_runner:35 sent - historical data request : ADSK 2010-01-01 2020-01-01
2020-02-08 01:23:27,440 DEBUG download_runner.impl.historical_runner:36 request accounted for...
2020-02-08 01:23:27,440 INFO download_runner.impl.historical_runner:37 status : True
2020-02-08 01:23:27,440 INFO download_runner.impl.historical_runner:42 Historical data request sent : ADSK 2010-01-01 2020-01-01
2020-02-08 01:23:27,441 DEBUG download_runner.impl.historical_end_reader:37 poll stock ? => True
2020-02-08 01:23:27,441 ERROR root:30 unhandled exception getting latest timestamp for ADSW
Traceback (most recent call last):
  File "/Users/dali/workspace/ib_python/runner/services/historical_data_service.py", line 24, in get_latest_timestamp
    response = self.stub.GetLatestTimeStamp(request)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 604, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 506, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1581125007.441238000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3876,"referenced_errors":[{"created":"@1581124926.851274000","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":395,"grpc_status":14}]}"
>
2020-02-08 01:23:27,441 INFO download_runner.impl.historical_runner:32 sending - historical data request : ADSW 2010-01-01 2020-01-01
2020-02-08 01:23:29,341 INFO download_runner.impl.historical_runner:35 sent - historical data request : ADSW 2010-01-01 2020-01-01
2020-02-08 01:23:29,341 DEBUG download_runner.impl.historical_runner:36 request accounted for...
2020-02-08 01:23:29,341 INFO download_runner.impl.historical_runner:37 status : True
2020-02-08 01:23:29,341 INFO download_runner.impl.historical_runner:42 Historical data request sent : ADSW 2010-01-01 2020-01-01
2020-02-08 01:23:29,341 DEBUG download_runner.impl.historical_end_reader:37 poll stock ? => True
2020-02-08 01:23:29,342 ERROR root:30 unhandled exception getting latest timestamp for ADT
Traceback (most recent call last):
  File "/Users/dali/workspace/ib_python/runner/services/historical_data_service.py", line 24, in get_latest_timestamp
    response = self.stub.GetLatestTimeStamp(request)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 604, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 506, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1581125009.342075000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3876,"referenced_errors":[{"created":"@1581124926.851274000","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":395,"grpc_status":14}]}"
>
2020-02-08 01:23:29,342 INFO download_runner.impl.historical_runner:32 sending - historical data request : ADT 2010-01-01 2020-01-01
2020-02-08 01:23:30,282 INFO download_runner.impl.historical_runner:35 sent - historical data request : ADT 2010-01-01 2020-01-01
2020-02-08 01:23:30,282 DEBUG download_runner.impl.historical_runner:36 request accounted for...
2020-02-08 01:23:30,283 INFO download_runner.impl.historical_runner:37 status : True
2020-02-08 01:23:30,283 INFO download_runner.impl.historical_runner:42 Historical data request sent : ADT 2010-01-01 2020-01-01
2020-02-08 01:23:30,283 DEBUG download_runner.impl.historical_end_reader:37 poll stock ? => True
2020-02-08 01:23:30,283 ERROR root:30 unhandled exception getting latest timestamp for ADTN
Traceback (most recent call last):
  File "/Users/dali/workspace/ib_python/runner/services/historical_data_service.py", line 24, in get_latest_timestamp
    response = self.stub.GetLatestTimeStamp(request)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 604, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 506, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1581125010.283305000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3876,"referenced_errors":[{"created":"@1581124926.851274000","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":395,"grpc_status":14}]}"
>
2020-02-08 01:23:30,283 INFO download_runner.impl.historical_runner:32 sending - historical data request : ADTN 2010-01-01 2020-01-01
2020-02-08 01:23:34,621 INFO download_runner.impl.historical_runner:35 sent - historical data request : ADTN 2010-01-01 2020-01-01
2020-02-08 01:23:34,621 DEBUG download_runner.impl.historical_runner:36 request accounted for...
2020-02-08 01:23:34,621 INFO download_runner.impl.historical_runner:37 status : True
2020-02-08 01:23:34,621 INFO download_runner.impl.historical_runner:42 Historical data request sent : ADTN 2010-01-01 2020-01-01
2020-02-08 01:23:34,621 DEBUG download_runner.impl.historical_end_reader:37 poll stock ? => True
2020-02-08 01:23:34,622 ERROR root:30 unhandled exception getting latest timestamp for ADUS
Traceback (most recent call last):
  File "/Users/dali/workspace/ib_python/runner/services/historical_data_service.py", line 24, in get_latest_timestamp
    response = self.stub.GetLatestTimeStamp(request)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 604, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 506, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1581125014.622202000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3876,"referenced_errors":[{"created":"@1581124926.851274000","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":395,"grpc_status":14}]}"
>
2020-02-08 01:23:34,622 INFO download_runner.impl.historical_runner:32 sending - historical data request : ADUS 2010-01-01 2020-01-01
2020-02-08 01:23:39,454 INFO download_runner.impl.historical_runner:35 sent - historical data request : ADUS 2010-01-01 2020-01-01
2020-02-08 01:23:39,454 DEBUG download_runner.impl.historical_runner:36 request accounted for...
2020-02-08 01:23:39,454 INFO download_runner.impl.historical_runner:37 status : True
2020-02-08 01:23:39,454 INFO download_runner.impl.historical_runner:42 Historical data request sent : ADUS 2010-01-01 2020-01-01
2020-02-08 01:23:39,454 DEBUG download_runner.impl.historical_end_reader:37 poll stock ? => True
2020-02-08 01:23:39,454 ERROR root:30 unhandled exception getting latest timestamp for ADVM
Traceback (most recent call last):
  File "/Users/dali/workspace/ib_python/runner/services/historical_data_service.py", line 24, in get_latest_timestamp
    response = self.stub.GetLatestTimeStamp(request)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 604, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 506, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1581125019.454642000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3876,"referenced_errors":[{"created":"@1581124926.851274000","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":395,"grpc_status":14}]}"
>
2020-02-08 01:23:39,454 INFO download_runner.impl.historical_runner:32 sending - historical data request : ADVM 2010-01-01 2020-01-01
2020-02-08 01:23:43,966 INFO download_runner.impl.historical_runner:35 sent - historical data request : ADVM 2010-01-01 2020-01-01
2020-02-08 01:23:43,966 DEBUG download_runner.impl.historical_runner:36 request accounted for...
2020-02-08 01:23:43,966 INFO download_runner.impl.historical_runner:37 status : True
2020-02-08 01:23:43,966 INFO download_runner.impl.historical_runner:42 Historical data request sent : ADVM 2010-01-01 2020-01-01
2020-02-08 01:23:43,966 DEBUG download_runner.impl.historical_end_reader:37 poll stock ? => True
2020-02-08 01:23:43,967 ERROR root:30 unhandled exception getting latest timestamp for ADX
Traceback (most recent call last):
  File "/Users/dali/workspace/ib_python/runner/services/historical_data_service.py", line 24, in get_latest_timestamp
    response = self.stub.GetLatestTimeStamp(request)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 604, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 506, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1581125023.967104000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3876,"referenced_errors":[{"created":"@1581124926.851274000","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":395,"grpc_status":14}]}"
>
2020-02-08 01:23:43,967 INFO download_runner.impl.historical_runner:32 sending - historical data request : ADX 2010-01-01 2020-01-01
2020-02-08 01:23:57,613 INFO download_runner.impl.historical_runner:35 sent - historical data request : ADX 2010-01-01 2020-01-01
2020-02-08 01:23:57,613 DEBUG download_runner.impl.historical_runner:36 request accounted for...
2020-02-08 01:23:57,613 INFO download_runner.impl.historical_runner:37 status : True
2020-02-08 01:23:57,613 INFO download_runner.impl.historical_runner:42 Historical data request sent : ADX 2010-01-01 2020-01-01
2020-02-08 01:23:57,613 DEBUG download_runner.impl.historical_end_reader:37 poll stock ? => True
2020-02-08 01:23:57,614 ERROR root:30 unhandled exception getting latest timestamp for ADXS
Traceback (most recent call last):
  File "/Users/dali/workspace/ib_python/runner/services/historical_data_service.py", line 24, in get_latest_timestamp
    response = self.stub.GetLatestTimeStamp(request)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 604, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 506, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1581125037.614079000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3876,"referenced_errors":[{"created":"@1581124926.851274000","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":395,"grpc_status":14}]}"
>
2020-02-08 01:23:57,614 INFO download_runner.impl.historical_runner:32 sending - historical data request : ADXS 2010-01-01 2020-01-01
2020-02-08 01:24:13,985 INFO download_runner.impl.historical_runner:35 sent - historical data request : ADXS 2010-01-01 2020-01-01
2020-02-08 01:24:13,985 DEBUG download_runner.impl.historical_runner:36 request accounted for...
2020-02-08 01:24:13,985 INFO download_runner.impl.historical_runner:37 status : True
2020-02-08 01:24:13,985 INFO download_runner.impl.historical_runner:42 Historical data request sent : ADXS 2010-01-01 2020-01-01
2020-02-08 01:24:13,985 DEBUG download_runner.impl.historical_end_reader:37 poll stock ? => True
2020-02-08 01:24:13,986 ERROR root:30 unhandled exception getting latest timestamp for AE
Traceback (most recent call last):
  File "/Users/dali/workspace/ib_python/runner/services/historical_data_service.py", line 24, in get_latest_timestamp
    response = self.stub.GetLatestTimeStamp(request)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 604, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 506, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1581125053.986125000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3876,"referenced_errors":[{"created":"@1581125053.986123000","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":395,"grpc_status":14}]}"
>
2020-02-08 01:24:13,986 INFO download_runner.impl.historical_runner:32 sending - historical data request : AE 2010-01-01 2020-01-01
2020-02-08 01:24:28,749 INFO download_runner.impl.historical_runner:35 sent - historical data request : AE 2010-01-01 2020-01-01
2020-02-08 01:24:28,749 DEBUG download_runner.impl.historical_runner:36 request accounted for...
2020-02-08 01:24:28,749 INFO download_runner.impl.historical_runner:37 status : True
2020-02-08 01:24:28,749 INFO download_runner.impl.historical_runner:42 Historical data request sent : AE 2010-01-01 2020-01-01
2020-02-08 01:24:28,749 DEBUG download_runner.impl.historical_end_reader:37 poll stock ? => True
2020-02-08 01:24:28,750 ERROR root:30 unhandled exception getting latest timestamp for AEB
Traceback (most recent call last):
  File "/Users/dali/workspace/ib_python/runner/services/historical_data_service.py", line 24, in get_latest_timestamp
    response = self.stub.GetLatestTimeStamp(request)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 604, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 506, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1581125068.750172000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3876,"referenced_errors":[{"created":"@1581125053.986123000","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":395,"grpc_status":14}]}"
>
2020-02-08 01:24:28,750 INFO download_runner.impl.historical_runner:32 sending - historical data request : AEB 2010-01-01 2020-01-01
2020-02-08 01:24:34,269 INFO download_runner.impl.historical_runner:35 sent - historical data request : AEB 2010-01-01 2020-01-01
2020-02-08 01:24:34,269 DEBUG download_runner.impl.historical_runner:36 request accounted for...
2020-02-08 01:24:34,269 INFO download_runner.impl.historical_runner:37 status : True
2020-02-08 01:24:34,269 INFO download_runner.impl.historical_runner:42 Historical data request sent : AEB 2010-01-01 2020-01-01
2020-02-08 01:24:34,269 DEBUG download_runner.impl.historical_end_reader:37 poll stock ? => True
2020-02-08 01:24:34,269 ERROR root:30 unhandled exception getting latest timestamp for AGM PRD
Traceback (most recent call last):
  File "/Users/dali/workspace/ib_python/runner/services/historical_data_service.py", line 24, in get_latest_timestamp
    response = self.stub.GetLatestTimeStamp(request)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 604, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 506, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1581125074.269794000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3876,"referenced_errors":[{"created":"@1581125053.986123000","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":395,"grpc_status":14}]}"
>
2020-02-08 01:24:34,270 INFO download_runner.impl.historical_runner:32 sending - historical data request : AGM PRD 2010-01-01 2020-01-01
2020-02-08 01:24:34,691 INFO download_runner.impl.historical_runner:35 sent - historical data request : AGM PRD 2010-01-01 2020-01-01
2020-02-08 01:24:34,692 DEBUG download_runner.impl.historical_runner:36 request accounted for...
2020-02-08 01:24:34,692 INFO download_runner.impl.historical_runner:37 status : True
2020-02-08 01:24:34,692 INFO download_runner.impl.historical_runner:42 Historical data request sent : AGM PRD 2010-01-01 2020-01-01
2020-02-08 01:24:34,692 DEBUG download_runner.impl.historical_end_reader:37 poll stock ? => True
2020-02-08 01:24:34,692 ERROR root:30 unhandled exception getting latest timestamp for AGMH
Traceback (most recent call last):
  File "/Users/dali/workspace/ib_python/runner/services/historical_data_service.py", line 24, in get_latest_timestamp
    response = self.stub.GetLatestTimeStamp(request)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 604, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 506, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1581125074.692373000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3876,"referenced_errors":[{"created":"@1581125053.986123000","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":395,"grpc_status":14}]}"
>
2020-02-08 01:24:34,692 INFO download_runner.impl.historical_runner:32 sending - historical data request : AGMH 2010-01-01 2020-01-01
2020-02-08 01:24:35,860 INFO download_runner.impl.historical_runner:35 sent - historical data request : AGMH 2010-01-01 2020-01-01
2020-02-08 01:24:35,860 DEBUG download_runner.impl.historical_runner:36 request accounted for...
2020-02-08 01:24:35,860 INFO download_runner.impl.historical_runner:37 status : True
2020-02-08 01:24:35,860 INFO download_runner.impl.historical_runner:42 Historical data request sent : AGMH 2010-01-01 2020-01-01
2020-02-08 01:24:35,860 DEBUG download_runner.impl.historical_end_reader:37 poll stock ? => True
2020-02-08 01:24:35,860 ERROR root:30 unhandled exception getting latest timestamp for AGN
Traceback (most recent call last):
  File "/Users/dali/workspace/ib_python/runner/services/historical_data_service.py", line 24, in get_latest_timestamp
    response = self.stub.GetLatestTimeStamp(request)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 604, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 506, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1581125075.860626000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3876,"referenced_errors":[{"created":"@1581125053.986123000","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":395,"grpc_status":14}]}"
>
2020-02-08 01:24:35,860 INFO download_runner.impl.historical_runner:32 sending - historical data request : AGN 2010-01-01 2020-01-01
2020-02-08 01:24:39,854 INFO download_runner.impl.historical_runner:35 sent - historical data request : AGN 2010-01-01 2020-01-01
2020-02-08 01:24:39,854 DEBUG download_runner.impl.historical_runner:36 request accounted for...
2020-02-08 01:24:39,854 INFO download_runner.impl.historical_runner:37 status : True
2020-02-08 01:24:39,854 INFO download_runner.impl.historical_runner:42 Historical data request sent : AGN 2010-01-01 2020-01-01
2020-02-08 01:24:39,854 DEBUG download_runner.impl.historical_end_reader:37 poll stock ? => True
2020-02-08 01:24:39,855 ERROR root:30 unhandled exception getting latest timestamp for AGNC
Traceback (most recent call last):
  File "/Users/dali/workspace/ib_python/runner/services/historical_data_service.py", line 24, in get_latest_timestamp
    response = self.stub.GetLatestTimeStamp(request)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 604, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 506, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1581125079.855045000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3876,"referenced_errors":[{"created":"@1581125053.986123000","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":395,"grpc_status":14}]}"
>
2020-02-08 01:24:39,855 INFO download_runner.impl.historical_runner:32 sending - historical data request : AGNC 2010-01-01 2020-01-01
2020-02-08 01:24:46,286 INFO download_runner.impl.historical_runner:35 sent - historical data request : AGNC 2010-01-01 2020-01-01
2020-02-08 01:24:46,286 DEBUG download_runner.impl.historical_runner:36 request accounted for...
2020-02-08 01:24:46,286 INFO download_runner.impl.historical_runner:37 status : True
2020-02-08 01:24:46,286 INFO download_runner.impl.historical_runner:42 Historical data request sent : AGNC 2010-01-01 2020-01-01
2020-02-08 01:24:46,287 DEBUG download_runner.impl.historical_end_reader:37 poll stock ? => True
2020-02-08 01:24:46,287 ERROR root:30 unhandled exception getting latest timestamp for AGNCB
Traceback (most recent call last):
  File "/Users/dali/workspace/ib_python/runner/services/historical_data_service.py", line 24, in get_latest_timestamp
    response = self.stub.GetLatestTimeStamp(request)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 604, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 506, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1581125086.287244000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3876,"referenced_errors":[{"created":"@1581125053.986123000","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":395,"grpc_status":14}]}"
>
2020-02-08 01:24:46,287 INFO download_runner.impl.historical_runner:32 sending - historical data request : AGNCB 2010-01-01 2020-01-01
2020-02-08 01:24:46,505 INFO download_runner.impl.historical_runner:35 sent - historical data request : AGNCB 2010-01-01 2020-01-01
2020-02-08 01:24:46,506 DEBUG download_runner.impl.historical_runner:36 request accounted for...
2020-02-08 01:24:46,506 INFO download_runner.impl.historical_runner:37 status : True
2020-02-08 01:24:46,506 INFO download_runner.impl.historical_runner:42 Historical data request sent : AGNCB 2010-01-01 2020-01-01
2020-02-08 01:24:46,506 DEBUG download_runner.impl.historical_end_reader:37 poll stock ? => True
2020-02-08 01:24:46,506 ERROR root:30 unhandled exception getting latest timestamp for AGNCM
Traceback (most recent call last):
  File "/Users/dali/workspace/ib_python/runner/services/historical_data_service.py", line 24, in get_latest_timestamp
    response = self.stub.GetLatestTimeStamp(request)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 604, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 506, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1581125086.506500000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3876,"referenced_errors":[{"created":"@1581125053.986123000","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":395,"grpc_status":14}]}"
>
2020-02-08 01:24:46,506 INFO download_runner.impl.historical_runner:32 sending - historical data request : AGNCM 2010-01-01 2020-01-01
2020-02-08 01:24:46,959 INFO download_runner.impl.historical_runner:35 sent - historical data request : AGNCM 2010-01-01 2020-01-01
2020-02-08 01:24:46,959 DEBUG download_runner.impl.historical_runner:36 request accounted for...
2020-02-08 01:24:46,959 INFO download_runner.impl.historical_runner:37 status : True
2020-02-08 01:24:46,959 INFO download_runner.impl.historical_runner:42 Historical data request sent : AGNCM 2010-01-01 2020-01-01
2020-02-08 01:24:46,959 DEBUG download_runner.impl.historical_end_reader:37 poll stock ? => True
2020-02-08 01:24:46,960 ERROR root:30 unhandled exception getting latest timestamp for AGNCN
Traceback (most recent call last):
  File "/Users/dali/workspace/ib_python/runner/services/historical_data_service.py", line 24, in get_latest_timestamp
    response = self.stub.GetLatestTimeStamp(request)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 604, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 506, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1581125086.960140000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3876,"referenced_errors":[{"created":"@1581125053.986123000","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":395,"grpc_status":14}]}"
>
2020-02-08 01:24:46,960 INFO download_runner.impl.historical_runner:32 sending - historical data request : AGNCN 2010-01-01 2020-01-01
2020-02-08 01:24:54,346 INFO download_runner.impl.historical_runner:35 sent - historical data request : AGNCN 2010-01-01 2020-01-01
2020-02-08 01:24:54,346 DEBUG download_runner.impl.historical_runner:36 request accounted for...
2020-02-08 01:24:54,346 INFO download_runner.impl.historical_runner:37 status : True
2020-02-08 01:24:54,346 INFO download_runner.impl.historical_runner:42 Historical data request sent : AGNCN 2010-01-01 2020-01-01
2020-02-08 01:24:54,346 DEBUG download_runner.impl.historical_end_reader:37 poll stock ? => True
2020-02-08 01:24:54,346 ERROR root:30 unhandled exception getting latest timestamp for AGNCO
Traceback (most recent call last):
  File "/Users/dali/workspace/ib_python/runner/services/historical_data_service.py", line 24, in get_latest_timestamp
    response = self.stub.GetLatestTimeStamp(request)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 604, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 506, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1581125094.346747000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3876,"referenced_errors":[{"created":"@1581125053.986123000","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":395,"grpc_status":14}]}"
>
2020-02-08 01:24:54,347 INFO download_runner.impl.historical_runner:32 sending - historical data request : AGNCO 2010-01-01 2020-01-01
2020-02-08 01:24:54,707 INFO download_runner.impl.historical_runner:35 sent - historical data request : AGNCO 2010-01-01 2020-01-01
2020-02-08 01:24:54,707 DEBUG download_runner.impl.historical_runner:36 request accounted for...
2020-02-08 01:24:54,707 INFO download_runner.impl.historical_runner:37 status : True
2020-02-08 01:24:54,707 INFO download_runner.impl.historical_runner:42 Historical data request sent : AGNCO 2010-01-01 2020-01-01
2020-02-08 01:24:54,707 DEBUG download_runner.impl.historical_end_reader:37 poll stock ? => True
2020-02-08 01:24:54,707 ERROR root:30 unhandled exception getting latest timestamp for AGND
Traceback (most recent call last):
  File "/Users/dali/workspace/ib_python/runner/services/historical_data_service.py", line 24, in get_latest_timestamp
    response = self.stub.GetLatestTimeStamp(request)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 604, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 506, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1581125094.707803000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3876,"referenced_errors":[{"created":"@1581125053.986123000","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":395,"grpc_status":14}]}"
>
2020-02-08 01:24:54,708 INFO download_runner.impl.historical_runner:32 sending - historical data request : AGND 2010-01-01 2020-01-01
2020-02-08 01:25:13,887 INFO download_runner.impl.historical_runner:35 sent - historical data request : AGND 2010-01-01 2020-01-01
2020-02-08 01:25:13,887 DEBUG download_runner.impl.historical_runner:36 request accounted for...
2020-02-08 01:25:13,887 INFO download_runner.impl.historical_runner:37 status : True
2020-02-08 01:25:13,887 INFO download_runner.impl.historical_runner:42 Historical data request sent : AGND 2010-01-01 2020-01-01
2020-02-08 01:25:13,887 DEBUG download_runner.impl.historical_end_reader:37 poll stock ? => True
2020-02-08 01:25:13,888 ERROR root:30 unhandled exception getting latest timestamp for AGO
Traceback (most recent call last):
  File "/Users/dali/workspace/ib_python/runner/services/historical_data_service.py", line 24, in get_latest_timestamp
    response = self.stub.GetLatestTimeStamp(request)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 604, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 506, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1581125113.888085000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3876,"referenced_errors":[{"created":"@1581125053.986123000","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":395,"grpc_status":14}]}"
>
2020-02-08 01:25:13,888 INFO download_runner.impl.historical_runner:32 sending - historical data request : AGO 2010-01-01 2020-01-01
2020-02-08 01:25:28,929 INFO download_runner.impl.historical_runner:35 sent - historical data request : AGO 2010-01-01 2020-01-01
2020-02-08 01:25:28,929 DEBUG download_runner.impl.historical_runner:36 request accounted for...
2020-02-08 01:25:28,929 INFO download_runner.impl.historical_runner:37 status : True
2020-02-08 01:25:28,929 INFO download_runner.impl.historical_runner:42 Historical data request sent : AGO 2010-01-01 2020-01-01
2020-02-08 01:25:28,929 DEBUG download_runner.impl.historical_end_reader:37 poll stock ? => True
2020-02-08 01:25:28,930 ERROR root:30 unhandled exception getting latest timestamp for AGO PRB
Traceback (most recent call last):
  File "/Users/dali/workspace/ib_python/runner/services/historical_data_service.py", line 24, in get_latest_timestamp
    response = self.stub.GetLatestTimeStamp(request)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 604, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 506, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1581125128.930031000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3876,"referenced_errors":[{"created":"@1581125053.986123000","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":395,"grpc_status":14}]}"
>
2020-02-08 01:25:28,930 INFO download_runner.impl.historical_runner:32 sending - historical data request : AGO PRB 2010-01-01 2020-01-01
2020-02-08 01:25:34,367 INFO download_runner.impl.historical_runner:35 sent - historical data request : AGO PRB 2010-01-01 2020-01-01
2020-02-08 01:25:34,367 DEBUG download_runner.impl.historical_runner:36 request accounted for...
2020-02-08 01:25:34,367 INFO download_runner.impl.historical_runner:37 status : True
2020-02-08 01:25:34,367 INFO download_runner.impl.historical_runner:42 Historical data request sent : AGO PRB 2010-01-01 2020-01-01
2020-02-08 01:25:34,367 DEBUG download_runner.impl.historical_end_reader:37 poll stock ? => True
2020-02-08 01:25:34,367 ERROR root:30 unhandled exception getting latest timestamp for AGO PRE
Traceback (most recent call last):
  File "/Users/dali/workspace/ib_python/runner/services/historical_data_service.py", line 24, in get_latest_timestamp
    response = self.stub.GetLatestTimeStamp(request)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 604, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 506, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1581125134.367684000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3876,"referenced_errors":[{"created":"@1581125053.986123000","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":395,"grpc_status":14}]}"
>
2020-02-08 01:25:34,367 INFO download_runner.impl.historical_runner:32 sending - historical data request : AGO PRE 2010-01-01 2020-01-01
2020-02-08 01:25:40,713 INFO download_runner.impl.historical_runner:35 sent - historical data request : AGO PRE 2010-01-01 2020-01-01
2020-02-08 01:25:40,713 DEBUG download_runner.impl.historical_runner:36 request accounted for...
2020-02-08 01:25:40,713 INFO download_runner.impl.historical_runner:37 status : True
2020-02-08 01:25:40,713 INFO download_runner.impl.historical_runner:42 Historical data request sent : AGO PRE 2010-01-01 2020-01-01
2020-02-08 01:25:40,713 DEBUG download_runner.impl.historical_end_reader:37 poll stock ? => True
2020-02-08 01:25:40,714 ERROR root:30 unhandled exception getting latest timestamp for AGO PRF
Traceback (most recent call last):
  File "/Users/dali/workspace/ib_python/runner/services/historical_data_service.py", line 24, in get_latest_timestamp
    response = self.stub.GetLatestTimeStamp(request)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 604, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 506, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1581125140.713939000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3876,"referenced_errors":[{"created":"@1581125053.986123000","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":395,"grpc_status":14}]}"
>
2020-02-08 01:25:40,714 INFO download_runner.impl.historical_runner:32 sending - historical data request : AGO PRF 2010-01-01 2020-01-01
2020-02-08 01:25:46,064 INFO download_runner.impl.historical_runner:35 sent - historical data request : AGO PRF 2010-01-01 2020-01-01
2020-02-08 01:25:46,064 DEBUG download_runner.impl.historical_runner:36 request accounted for...
2020-02-08 01:25:46,064 INFO download_runner.impl.historical_runner:37 status : True
2020-02-08 01:25:46,064 INFO download_runner.impl.historical_runner:42 Historical data request sent : AGO PRF 2010-01-01 2020-01-01
2020-02-08 01:25:46,064 DEBUG download_runner.impl.historical_end_reader:37 poll stock ? => True
2020-02-08 01:25:46,065 ERROR root:30 unhandled exception getting latest timestamp for AGQ
Traceback (most recent call last):
  File "/Users/dali/workspace/ib_python/runner/services/historical_data_service.py", line 24, in get_latest_timestamp
    response = self.stub.GetLatestTimeStamp(request)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 604, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 506, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1581125146.065163000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3876,"referenced_errors":[{"created":"@1581125053.986123000","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":395,"grpc_status":14}]}"
>
2020-02-08 01:25:46,065 INFO download_runner.impl.historical_runner:32 sending - historical data request : AGQ 2010-01-01 2020-01-01
2020-02-08 01:25:52,980 INFO download_runner.impl.historical_runner:35 sent - historical data request : AGQ 2010-01-01 2020-01-01
2020-02-08 01:25:52,980 DEBUG download_runner.impl.historical_runner:36 request accounted for...
2020-02-08 01:25:52,980 INFO download_runner.impl.historical_runner:37 status : True
2020-02-08 01:25:52,980 INFO download_runner.impl.historical_runner:42 Historical data request sent : AGQ 2010-01-01 2020-01-01
2020-02-08 01:25:52,980 DEBUG download_runner.impl.historical_end_reader:37 poll stock ? => True
2020-02-08 01:25:52,980 ERROR root:30 unhandled exception getting latest timestamp for AGR
Traceback (most recent call last):
  File "/Users/dali/workspace/ib_python/runner/services/historical_data_service.py", line 24, in get_latest_timestamp
    response = self.stub.GetLatestTimeStamp(request)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 604, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 506, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1581125152.980552000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3876,"referenced_errors":[{"created":"@1581125053.986123000","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":395,"grpc_status":14}]}"
>
2020-02-08 01:25:52,980 INFO download_runner.impl.historical_runner:32 sending - historical data request : AGR 2010-01-01 2020-01-01
2020-02-08 01:26:01,915 INFO download_runner.impl.historical_runner:35 sent - historical data request : AGR 2010-01-01 2020-01-01
2020-02-08 01:26:01,915 DEBUG download_runner.impl.historical_runner:36 request accounted for...
2020-02-08 01:26:01,915 INFO download_runner.impl.historical_runner:37 status : True
2020-02-08 01:26:01,915 INFO download_runner.impl.historical_runner:42 Historical data request sent : AGR 2010-01-01 2020-01-01
2020-02-08 01:26:01,915 DEBUG download_runner.impl.historical_end_reader:37 poll stock ? => True
2020-02-08 01:26:01,915 ERROR root:30 unhandled exception getting latest timestamp for AGRO
Traceback (most recent call last):
  File "/Users/dali/workspace/ib_python/runner/services/historical_data_service.py", line 24, in get_latest_timestamp
    response = self.stub.GetLatestTimeStamp(request)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 604, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 506, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1581125161.915812000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3876,"referenced_errors":[{"created":"@1581125053.986123000","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":395,"grpc_status":14}]}"
>
2020-02-08 01:26:01,916 INFO download_runner.impl.historical_runner:32 sending - historical data request : AGRO 2010-01-01 2020-01-01
2020-02-08 01:26:28,159 INFO download_runner.impl.historical_runner:35 sent - historical data request : AGRO 2010-01-01 2020-01-01
2020-02-08 01:26:28,159 DEBUG download_runner.impl.historical_runner:36 request accounted for...
2020-02-08 01:26:28,159 INFO download_runner.impl.historical_runner:37 status : True
2020-02-08 01:26:28,159 INFO download_runner.impl.historical_runner:42 Historical data request sent : AGRO 2010-01-01 2020-01-01
2020-02-08 01:26:28,159 DEBUG download_runner.impl.historical_end_reader:37 poll stock ? => True
2020-02-08 01:26:28,160 ERROR root:30 unhandled exception getting latest timestamp for AGRX
Traceback (most recent call last):
  File "/Users/dali/workspace/ib_python/runner/services/historical_data_service.py", line 24, in get_latest_timestamp
    response = self.stub.GetLatestTimeStamp(request)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 604, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 506, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1581125188.160054000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3876,"referenced_errors":[{"created":"@1581125053.986123000","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":395,"grpc_status":14}]}"
>
2020-02-08 01:26:28,160 INFO download_runner.impl.historical_runner:32 sending - historical data request : AGRX 2010-01-01 2020-01-01
2020-02-08 01:26:31,648 INFO download_runner.impl.historical_runner:35 sent - historical data request : AGRX 2010-01-01 2020-01-01
2020-02-08 01:26:31,649 DEBUG download_runner.impl.historical_runner:36 request accounted for...
2020-02-08 01:26:31,649 INFO download_runner.impl.historical_runner:37 status : True
2020-02-08 01:26:31,649 INFO download_runner.impl.historical_runner:42 Historical data request sent : AGRX 2010-01-01 2020-01-01
2020-02-08 01:26:31,649 DEBUG download_runner.impl.historical_end_reader:37 poll stock ? => True
2020-02-08 01:26:31,649 ERROR root:30 unhandled exception getting latest timestamp for AGS
Traceback (most recent call last):
  File "/Users/dali/workspace/ib_python/runner/services/historical_data_service.py", line 24, in get_latest_timestamp
    response = self.stub.GetLatestTimeStamp(request)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 604, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 506, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1581125191.649507000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3876,"referenced_errors":[{"created":"@1581125191.649505000","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":395,"grpc_status":14}]}"
>
2020-02-08 01:26:31,649 INFO download_runner.impl.historical_runner:32 sending - historical data request : AGS 2010-01-01 2020-01-01
2020-02-08 01:26:32,835 INFO download_runner.impl.historical_runner:35 sent - historical data request : AGS 2010-01-01 2020-01-01
2020-02-08 01:26:32,835 DEBUG download_runner.impl.historical_runner:36 request accounted for...
2020-02-08 01:26:32,835 INFO download_runner.impl.historical_runner:37 status : True
2020-02-08 01:26:32,835 INFO download_runner.impl.historical_runner:42 Historical data request sent : AGS 2010-01-01 2020-01-01
2020-02-08 01:26:32,835 DEBUG download_runner.impl.historical_end_reader:37 poll stock ? => True
2020-02-08 01:26:32,836 ERROR root:30 unhandled exception getting latest timestamp for AGT
Traceback (most recent call last):
  File "/Users/dali/workspace/ib_python/runner/services/historical_data_service.py", line 24, in get_latest_timestamp
    response = self.stub.GetLatestTimeStamp(request)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 604, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 506, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1581125192.836093000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3876,"referenced_errors":[{"created":"@1581125191.649505000","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":395,"grpc_status":14}]}"
>
2020-02-08 01:26:32,836 INFO download_runner.impl.historical_runner:32 sending - historical data request : AGT 2010-01-01 2020-01-01
2020-02-08 01:26:34,648 INFO download_runner.impl.historical_runner:35 sent - historical data request : AGT 2010-01-01 2020-01-01
2020-02-08 01:26:34,648 DEBUG download_runner.impl.historical_runner:36 request accounted for...
2020-02-08 01:26:34,649 INFO download_runner.impl.historical_runner:37 status : True
2020-02-08 01:26:34,649 INFO download_runner.impl.historical_runner:42 Historical data request sent : AGT 2010-01-01 2020-01-01
2020-02-08 01:26:34,649 DEBUG download_runner.impl.historical_end_reader:37 poll stock ? => True
2020-02-08 01:26:34,649 ERROR root:30 unhandled exception getting latest timestamp for AGTC
Traceback (most recent call last):
  File "/Users/dali/workspace/ib_python/runner/services/historical_data_service.py", line 24, in get_latest_timestamp
    response = self.stub.GetLatestTimeStamp(request)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 604, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 506, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1581125194.649308000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3876,"referenced_errors":[{"created":"@1581125191.649505000","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":395,"grpc_status":14}]}"
>
2020-02-08 01:26:34,649 INFO download_runner.impl.historical_runner:32 sending - historical data request : AGTC 2010-01-01 2020-01-01
2020-02-08 01:26:37,748 INFO download_runner.impl.historical_runner:35 sent - historical data request : AGTC 2010-01-01 2020-01-01
2020-02-08 01:26:37,748 DEBUG download_runner.impl.historical_runner:36 request accounted for...
2020-02-08 01:26:37,748 INFO download_runner.impl.historical_runner:37 status : True
2020-02-08 01:26:37,748 INFO download_runner.impl.historical_runner:42 Historical data request sent : AGTC 2010-01-01 2020-01-01
2020-02-08 01:26:37,748 DEBUG download_runner.impl.historical_end_reader:37 poll stock ? => True
2020-02-08 01:26:37,748 ERROR root:30 unhandled exception getting latest timestamp for AGX
Traceback (most recent call last):
  File "/Users/dali/workspace/ib_python/runner/services/historical_data_service.py", line 24, in get_latest_timestamp
    response = self.stub.GetLatestTimeStamp(request)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 604, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 506, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1581125197.748698000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3876,"referenced_errors":[{"created":"@1581125191.649505000","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":395,"grpc_status":14}]}"
>
2020-02-08 01:26:37,749 INFO download_runner.impl.historical_runner:32 sending - historical data request : AGX 2010-01-01 2020-01-01
2020-02-08 01:26:43,857 INFO download_runner.impl.historical_runner:35 sent - historical data request : AGX 2010-01-01 2020-01-01
2020-02-08 01:26:43,857 DEBUG download_runner.impl.historical_runner:36 request accounted for...
2020-02-08 01:26:43,857 INFO download_runner.impl.historical_runner:37 status : True
2020-02-08 01:26:43,857 INFO download_runner.impl.historical_runner:42 Historical data request sent : AGX 2010-01-01 2020-01-01
2020-02-08 01:26:43,858 DEBUG download_runner.impl.historical_end_reader:37 poll stock ? => True
2020-02-08 01:26:43,858 ERROR root:30 unhandled exception getting latest timestamp for AGYS
Traceback (most recent call last):
  File "/Users/dali/workspace/ib_python/runner/services/historical_data_service.py", line 24, in get_latest_timestamp
    response = self.stub.GetLatestTimeStamp(request)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 604, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 506, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1581125203.858244000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3876,"referenced_errors":[{"created":"@1581125191.649505000","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":395,"grpc_status":14}]}"
>
2020-02-08 01:26:43,858 INFO download_runner.impl.historical_runner:32 sending - historical data request : AGYS 2010-01-01 2020-01-01
2020-02-08 01:27:22,954 INFO download_runner.impl.historical_runner:35 sent - historical data request : AGYS 2010-01-01 2020-01-01
2020-02-08 01:27:22,954 DEBUG download_runner.impl.historical_runner:36 request accounted for...
2020-02-08 01:27:22,954 INFO download_runner.impl.historical_runner:37 status : True
2020-02-08 01:27:22,954 INFO download_runner.impl.historical_runner:42 Historical data request sent : AGYS 2010-01-01 2020-01-01
2020-02-08 01:27:22,954 DEBUG download_runner.impl.historical_end_reader:37 poll stock ? => True
2020-02-08 01:27:22,954 ERROR root:30 unhandled exception getting latest timestamp for AGZ
Traceback (most recent call last):
  File "/Users/dali/workspace/ib_python/runner/services/historical_data_service.py", line 24, in get_latest_timestamp
    response = self.stub.GetLatestTimeStamp(request)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 604, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 506, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1581125242.954841000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3876,"referenced_errors":[{"created":"@1581125191.649505000","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":395,"grpc_status":14}]}"
>
2020-02-08 01:27:22,955 INFO download_runner.impl.historical_runner:32 sending - historical data request : AGZ 2010-01-01 2020-01-01
