2020-02-08 12:15:20,981 DEBUG download_runner.impl.historical_end_reader:37 poll stock ? => True
2020-02-08 12:15:21,092 ERROR root:30 unhandled exception getting latest timestamp for AEE
Traceback (most recent call last):
  File "/Users/dali/workspace/ib_python/runner/services/historical_data_service.py", line 24, in get_latest_timestamp
    response = self.stub.GetLatestTimeStamp(request)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 604, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 506, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1581164121.092255000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3876,"referenced_errors":[{"created":"@1581164121.092254000","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":395,"grpc_status":14}]}"
>
2020-02-08 12:15:21,093 INFO download_runner.impl.historical_runner:32 sending - historical data request : AEE 2019-01-01 2020-01-01
2020-02-08 12:15:23,808 INFO download_runner.impl.historical_runner:35 sent - historical data request : AEE 2019-01-01 2020-01-01
2020-02-08 12:15:23,809 DEBUG download_runner.impl.historical_runner:36 request accounted for...
2020-02-08 12:15:23,809 INFO download_runner.impl.historical_runner:37 status : True
2020-02-08 12:15:23,809 INFO download_runner.impl.historical_runner:42 Historical data request sent : AEE 2019-01-01 2020-01-01
2020-02-08 12:15:23,809 DEBUG download_runner.impl.historical_end_reader:37 poll stock ? => True
2020-02-08 12:15:23,809 ERROR root:30 unhandled exception getting latest timestamp for A
Traceback (most recent call last):
  File "/Users/dali/workspace/ib_python/runner/services/historical_data_service.py", line 24, in get_latest_timestamp
    response = self.stub.GetLatestTimeStamp(request)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 604, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 506, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1581164123.809483000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3876,"referenced_errors":[{"created":"@1581164123.809482000","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":395,"grpc_status":14}]}"
>
2020-02-08 12:15:23,809 INFO download_runner.impl.historical_runner:32 sending - historical data request : A 2019-01-01 2020-01-01
2020-02-08 12:15:25,916 INFO download_runner.impl.historical_runner:35 sent - historical data request : A 2019-01-01 2020-01-01
2020-02-08 12:15:25,916 DEBUG download_runner.impl.historical_runner:36 request accounted for...
2020-02-08 12:15:25,916 INFO download_runner.impl.historical_runner:37 status : True
2020-02-08 12:15:25,916 INFO download_runner.impl.historical_runner:42 Historical data request sent : A 2019-01-01 2020-01-01
2020-02-08 12:15:25,916 DEBUG download_runner.impl.historical_end_reader:37 poll stock ? => True
2020-02-08 12:15:25,917 ERROR root:30 unhandled exception getting latest timestamp for AA
Traceback (most recent call last):
  File "/Users/dali/workspace/ib_python/runner/services/historical_data_service.py", line 24, in get_latest_timestamp
    response = self.stub.GetLatestTimeStamp(request)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 604, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 506, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1581164125.917113000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3876,"referenced_errors":[{"created":"@1581164125.917111000","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":395,"grpc_status":14}]}"
>
2020-02-08 12:15:25,917 INFO download_runner.impl.historical_runner:32 sending - historical data request : AA 2019-01-01 2020-01-01
2020-02-08 12:15:27,894 INFO download_runner.impl.historical_runner:35 sent - historical data request : AA 2019-01-01 2020-01-01
2020-02-08 12:15:27,894 DEBUG download_runner.impl.historical_runner:36 request accounted for...
2020-02-08 12:15:27,894 INFO download_runner.impl.historical_runner:37 status : True
2020-02-08 12:15:27,894 INFO download_runner.impl.historical_runner:42 Historical data request sent : AA 2019-01-01 2020-01-01
2020-02-08 12:15:27,894 DEBUG download_runner.impl.historical_end_reader:37 poll stock ? => True
2020-02-08 12:15:27,894 ERROR root:30 unhandled exception getting latest timestamp for AAAU
Traceback (most recent call last):
  File "/Users/dali/workspace/ib_python/runner/services/historical_data_service.py", line 24, in get_latest_timestamp
    response = self.stub.GetLatestTimeStamp(request)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 604, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 506, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1581164127.894829000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3876,"referenced_errors":[{"created":"@1581164127.894827000","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":395,"grpc_status":14}]}"
>
2020-02-08 12:15:27,895 INFO download_runner.impl.historical_runner:32 sending - historical data request : AAAU 2019-01-01 2020-01-01
2020-02-08 12:15:29,396 INFO download_runner.impl.historical_runner:35 sent - historical data request : AAAU 2019-01-01 2020-01-01
2020-02-08 12:15:29,396 DEBUG download_runner.impl.historical_runner:36 request accounted for...
2020-02-08 12:15:29,396 INFO download_runner.impl.historical_runner:37 status : True
2020-02-08 12:15:29,396 INFO download_runner.impl.historical_runner:42 Historical data request sent : AAAU 2019-01-01 2020-01-01
2020-02-08 12:15:29,396 DEBUG download_runner.impl.historical_end_reader:37 poll stock ? => True
2020-02-08 12:15:29,396 ERROR root:30 unhandled exception getting latest timestamp for AACG
Traceback (most recent call last):
  File "/Users/dali/workspace/ib_python/runner/services/historical_data_service.py", line 24, in get_latest_timestamp
    response = self.stub.GetLatestTimeStamp(request)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 604, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 506, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1581164129.396522000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3876,"referenced_errors":[{"created":"@1581164127.894827000","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":395,"grpc_status":14}]}"
>
2020-02-08 12:15:29,396 INFO download_runner.impl.historical_runner:32 sending - historical data request : AACG 2019-01-01 2020-01-01
2020-02-08 12:15:30,956 INFO download_runner.impl.historical_runner:35 sent - historical data request : AACG 2019-01-01 2020-01-01
2020-02-08 12:15:30,956 DEBUG download_runner.impl.historical_runner:36 request accounted for...
2020-02-08 12:15:30,956 INFO download_runner.impl.historical_runner:37 status : True
2020-02-08 12:15:30,956 INFO download_runner.impl.historical_runner:42 Historical data request sent : AACG 2019-01-01 2020-01-01
2020-02-08 12:15:30,956 DEBUG download_runner.impl.historical_end_reader:37 poll stock ? => True
2020-02-08 12:15:30,957 ERROR root:30 unhandled exception getting latest timestamp for AADR
Traceback (most recent call last):
  File "/Users/dali/workspace/ib_python/runner/services/historical_data_service.py", line 24, in get_latest_timestamp
    response = self.stub.GetLatestTimeStamp(request)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 604, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 506, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1581164130.957056000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3876,"referenced_errors":[{"created":"@1581164130.957055000","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":395,"grpc_status":14}]}"
>
2020-02-08 12:15:30,957 INFO download_runner.impl.historical_runner:32 sending - historical data request : AADR 2019-01-01 2020-01-01
2020-02-08 12:15:32,670 INFO download_runner.impl.historical_runner:35 sent - historical data request : AADR 2019-01-01 2020-01-01
2020-02-08 12:15:32,670 DEBUG download_runner.impl.historical_runner:36 request accounted for...
2020-02-08 12:15:32,670 INFO download_runner.impl.historical_runner:37 status : True
2020-02-08 12:15:32,670 INFO download_runner.impl.historical_runner:42 Historical data request sent : AADR 2019-01-01 2020-01-01
2020-02-08 12:15:32,670 DEBUG download_runner.impl.historical_end_reader:37 poll stock ? => True
2020-02-08 12:15:32,671 ERROR root:30 unhandled exception getting latest timestamp for AAL
Traceback (most recent call last):
  File "/Users/dali/workspace/ib_python/runner/services/historical_data_service.py", line 24, in get_latest_timestamp
    response = self.stub.GetLatestTimeStamp(request)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 604, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 506, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1581164132.671067000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3876,"referenced_errors":[{"created":"@1581164130.957055000","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":395,"grpc_status":14}]}"
>
2020-02-08 12:15:32,671 INFO download_runner.impl.historical_runner:32 sending - historical data request : AAL 2019-01-01 2020-01-01
2020-02-08 12:15:34,371 INFO download_runner.impl.historical_runner:35 sent - historical data request : AAL 2019-01-01 2020-01-01
2020-02-08 12:15:34,371 DEBUG download_runner.impl.historical_runner:36 request accounted for...
2020-02-08 12:15:34,371 INFO download_runner.impl.historical_runner:37 status : True
2020-02-08 12:15:34,371 INFO download_runner.impl.historical_runner:42 Historical data request sent : AAL 2019-01-01 2020-01-01
2020-02-08 12:15:34,371 DEBUG download_runner.impl.historical_end_reader:37 poll stock ? => True
2020-02-08 12:15:34,371 ERROR root:30 unhandled exception getting latest timestamp for AAMC
Traceback (most recent call last):
  File "/Users/dali/workspace/ib_python/runner/services/historical_data_service.py", line 24, in get_latest_timestamp
    response = self.stub.GetLatestTimeStamp(request)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 604, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 506, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1581164134.371671000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3876,"referenced_errors":[{"created":"@1581164130.957055000","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":395,"grpc_status":14}]}"
>
2020-02-08 12:15:34,372 INFO download_runner.impl.historical_runner:32 sending - historical data request : AAMC 2019-01-01 2020-01-01
2020-02-08 12:15:36,032 INFO download_runner.impl.historical_runner:35 sent - historical data request : AAMC 2019-01-01 2020-01-01
2020-02-08 12:15:36,033 DEBUG download_runner.impl.historical_runner:36 request accounted for...
2020-02-08 12:15:36,033 INFO download_runner.impl.historical_runner:37 status : True
2020-02-08 12:15:36,033 INFO download_runner.impl.historical_runner:42 Historical data request sent : AAMC 2019-01-01 2020-01-01
2020-02-08 12:15:36,033 DEBUG download_runner.impl.historical_end_reader:37 poll stock ? => True
2020-02-08 12:15:36,033 ERROR root:30 unhandled exception getting latest timestamp for AAME
Traceback (most recent call last):
  File "/Users/dali/workspace/ib_python/runner/services/historical_data_service.py", line 24, in get_latest_timestamp
    response = self.stub.GetLatestTimeStamp(request)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 604, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 506, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1581164136.033364000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3876,"referenced_errors":[{"created":"@1581164130.957055000","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":395,"grpc_status":14}]}"
>
2020-02-08 12:15:36,033 INFO download_runner.impl.historical_runner:32 sending - historical data request : AAME 2019-01-01 2020-01-01
2020-02-08 12:15:37,705 INFO download_runner.impl.historical_runner:35 sent - historical data request : AAME 2019-01-01 2020-01-01
2020-02-08 12:15:37,705 DEBUG download_runner.impl.historical_runner:36 request accounted for...
2020-02-08 12:15:37,705 INFO download_runner.impl.historical_runner:37 status : True
2020-02-08 12:15:37,705 INFO download_runner.impl.historical_runner:42 Historical data request sent : AAME 2019-01-01 2020-01-01
2020-02-08 12:15:37,705 DEBUG download_runner.impl.historical_end_reader:37 poll stock ? => True
2020-02-08 12:15:37,705 ERROR root:30 unhandled exception getting latest timestamp for AAN
Traceback (most recent call last):
  File "/Users/dali/workspace/ib_python/runner/services/historical_data_service.py", line 24, in get_latest_timestamp
    response = self.stub.GetLatestTimeStamp(request)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 604, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 506, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1581164137.705581000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3876,"referenced_errors":[{"created":"@1581164130.957055000","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":395,"grpc_status":14}]}"
>
2020-02-08 12:15:37,705 INFO download_runner.impl.historical_runner:32 sending - historical data request : AAN 2019-01-01 2020-01-01
2020-02-08 12:15:39,773 INFO download_runner.impl.historical_runner:35 sent - historical data request : AAN 2019-01-01 2020-01-01
2020-02-08 12:15:39,773 DEBUG download_runner.impl.historical_runner:36 request accounted for...
2020-02-08 12:15:39,773 INFO download_runner.impl.historical_runner:37 status : True
2020-02-08 12:15:39,773 INFO download_runner.impl.historical_runner:42 Historical data request sent : AAN 2019-01-01 2020-01-01
2020-02-08 12:15:39,773 DEBUG download_runner.impl.historical_end_reader:37 poll stock ? => True
2020-02-08 12:15:39,773 ERROR root:30 unhandled exception getting latest timestamp for AAOI
Traceback (most recent call last):
  File "/Users/dali/workspace/ib_python/runner/services/historical_data_service.py", line 24, in get_latest_timestamp
    response = self.stub.GetLatestTimeStamp(request)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 604, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 506, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1581164139.773859000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3876,"referenced_errors":[{"created":"@1581164139.773857000","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":395,"grpc_status":14}]}"
>
2020-02-08 12:15:39,774 INFO download_runner.impl.historical_runner:32 sending - historical data request : AAOI 2019-01-01 2020-01-01
