2020-02-08 13:00:01,082 DEBUG download_runner.impl.historical_end_reader:37 poll stock ? => True
2020-02-08 13:00:01,186 ERROR root:30 unhandled exception getting latest timestamp for ACIA
Traceback (most recent call last):
  File "/Users/dali/workspace/ib_python/runner/services/historical_data_service.py", line 24, in get_latest_timestamp
    response = self.stub.GetLatestTimeStamp(request)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 604, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 506, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1581166801.186546000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3876,"referenced_errors":[{"created":"@1581166801.186545000","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":395,"grpc_status":14}]}"
>
2020-02-08 13:00:01,188 INFO download_runner.impl.historical_runner:32 sending - historical data request : ACIA 2019-12-01 2020-01-01
2020-02-08 13:00:03,161 INFO download_runner.impl.historical_runner:35 sent - historical data request : ACIA 2019-12-01 2020-01-01
2020-02-08 13:00:03,161 DEBUG download_runner.impl.historical_runner:36 request accounted for...
2020-02-08 13:00:03,161 INFO download_runner.impl.historical_runner:37 status : True
2020-02-08 13:00:03,161 INFO download_runner.impl.historical_runner:42 Historical data request sent : ACIA 2019-12-01 2020-01-01
2020-02-08 13:00:03,161 DEBUG download_runner.impl.historical_end_reader:37 poll stock ? => True
2020-02-08 13:00:03,161 ERROR root:30 unhandled exception getting latest timestamp for AEE
Traceback (most recent call last):
  File "/Users/dali/workspace/ib_python/runner/services/historical_data_service.py", line 24, in get_latest_timestamp
    response = self.stub.GetLatestTimeStamp(request)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 604, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 506, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1581166803.161930000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3876,"referenced_errors":[{"created":"@1581166803.161929000","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":395,"grpc_status":14}]}"
>
2020-02-08 13:00:03,162 INFO download_runner.impl.historical_runner:32 sending - historical data request : AEE 2019-12-01 2020-01-01
2020-02-08 13:00:04,809 INFO download_runner.impl.historical_runner:35 sent - historical data request : AEE 2019-12-01 2020-01-01
2020-02-08 13:00:04,809 DEBUG download_runner.impl.historical_runner:36 request accounted for...
2020-02-08 13:00:04,809 INFO download_runner.impl.historical_runner:37 status : True
2020-02-08 13:00:04,810 INFO download_runner.impl.historical_runner:42 Historical data request sent : AEE 2019-12-01 2020-01-01
2020-02-08 13:00:04,810 DEBUG download_runner.impl.historical_end_reader:37 poll stock ? => True
2020-02-08 13:00:04,811 ERROR root:30 unhandled exception getting latest timestamp for AEF
Traceback (most recent call last):
  File "/Users/dali/workspace/ib_python/runner/services/historical_data_service.py", line 24, in get_latest_timestamp
    response = self.stub.GetLatestTimeStamp(request)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 604, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 506, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1581166804.811078000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3876,"referenced_errors":[{"created":"@1581166804.811073000","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":395,"grpc_status":14}]}"
>
2020-02-08 13:00:04,811 INFO download_runner.impl.historical_runner:32 sending - historical data request : AEF 2019-12-01 2020-01-01
2020-02-08 13:00:06,065 INFO download_runner.impl.historical_runner:35 sent - historical data request : AEF 2019-12-01 2020-01-01
2020-02-08 13:00:06,065 DEBUG download_runner.impl.historical_runner:36 request accounted for...
2020-02-08 13:00:06,065 INFO download_runner.impl.historical_runner:37 status : True
2020-02-08 13:00:06,065 INFO download_runner.impl.historical_runner:42 Historical data request sent : AEF 2019-12-01 2020-01-01
2020-02-08 13:00:06,065 DEBUG download_runner.impl.historical_end_reader:37 poll stock ? => True
2020-02-08 13:00:06,066 ERROR root:30 unhandled exception getting latest timestamp for AEFC
Traceback (most recent call last):
  File "/Users/dali/workspace/ib_python/runner/services/historical_data_service.py", line 24, in get_latest_timestamp
    response = self.stub.GetLatestTimeStamp(request)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 604, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 506, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1581166806.066133000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3876,"referenced_errors":[{"created":"@1581166804.811073000","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":395,"grpc_status":14}]}"
>
2020-02-08 13:00:06,067 INFO download_runner.impl.historical_runner:32 sending - historical data request : AEFC 2019-12-01 2020-01-01
2020-02-08 13:00:07,517 INFO download_runner.impl.historical_runner:35 sent - historical data request : AEFC 2019-12-01 2020-01-01
2020-02-08 13:00:07,518 DEBUG download_runner.impl.historical_runner:36 request accounted for...
2020-02-08 13:00:07,518 INFO download_runner.impl.historical_runner:37 status : True
2020-02-08 13:00:07,518 INFO download_runner.impl.historical_runner:42 Historical data request sent : AEFC 2019-12-01 2020-01-01
2020-02-08 13:00:07,518 DEBUG download_runner.impl.historical_end_reader:37 poll stock ? => True
2020-02-08 13:00:07,518 ERROR root:30 unhandled exception getting latest timestamp for AEG
Traceback (most recent call last):
  File "/Users/dali/workspace/ib_python/runner/services/historical_data_service.py", line 24, in get_latest_timestamp
    response = self.stub.GetLatestTimeStamp(request)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 604, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 506, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1581166807.518388000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3876,"referenced_errors":[{"created":"@1581166807.518387000","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":395,"grpc_status":14}]}"
>
2020-02-08 13:00:07,518 INFO download_runner.impl.historical_runner:32 sending - historical data request : AEG 2019-12-01 2020-01-01
2020-02-08 13:00:36,086 INFO download_runner.impl.historical_runner:35 sent - historical data request : AEG 2019-12-01 2020-01-01
2020-02-08 13:00:36,087 DEBUG download_runner.impl.historical_runner:36 request accounted for...
2020-02-08 13:00:36,087 INFO download_runner.impl.historical_runner:37 status : True
2020-02-08 13:00:36,087 INFO download_runner.impl.historical_runner:42 Historical data request sent : AEG 2019-12-01 2020-01-01
2020-02-08 13:00:36,087 DEBUG download_runner.impl.historical_end_reader:37 poll stock ? => True
2020-02-08 13:00:36,088 ERROR root:30 unhandled exception getting latest timestamp for AEGN
Traceback (most recent call last):
  File "/Users/dali/workspace/ib_python/runner/services/historical_data_service.py", line 24, in get_latest_timestamp
    response = self.stub.GetLatestTimeStamp(request)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 604, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 506, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1581166836.088008000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3876,"referenced_errors":[{"created":"@1581166831.093514000","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":395,"grpc_status":14}]}"
>
2020-02-08 13:00:36,088 INFO download_runner.impl.historical_runner:32 sending - historical data request : AEGN 2019-12-01 2020-01-01
