2020-02-08 01:02:08,703 DEBUG download_runner.impl.historical_end_reader:37 poll stock ? => True
2020-02-08 01:02:08,812 ERROR root:30 unhandled exception getting latest timestamp for ACIA
Traceback (most recent call last):
  File "/Users/dali/workspace/ib_python/runner/services/historical_data_service.py", line 24, in get_latest_timestamp
    response = self.stub.GetLatestTimeStamp(request)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 604, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 506, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1581123728.812548000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3876,"referenced_errors":[{"created":"@1581123728.812547000","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":395,"grpc_status":14}]}"
>
2020-02-08 01:02:08,814 INFO download_runner.impl.historical_runner:32 sending - historical data request : ACIA 2019-01-01 2020-01-01
2020-02-08 01:02:10,423 INFO download_runner.impl.historical_runner:35 sent - historical data request : ACIA 2019-01-01 2020-01-01
2020-02-08 01:02:10,423 DEBUG download_runner.impl.historical_runner:36 request accounted for...
2020-02-08 01:02:10,424 INFO download_runner.impl.historical_runner:37 status : True
2020-02-08 01:02:10,424 INFO download_runner.impl.historical_runner:42 Historical data request sent : ACIA 2019-01-01 2020-01-01
2020-02-08 01:02:10,424 DEBUG download_runner.impl.historical_end_reader:37 poll stock ? => True
2020-02-08 01:02:10,424 ERROR root:30 unhandled exception getting latest timestamp for A
Traceback (most recent call last):
  File "/Users/dali/workspace/ib_python/runner/services/historical_data_service.py", line 24, in get_latest_timestamp
    response = self.stub.GetLatestTimeStamp(request)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 604, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 506, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1581123730.424382000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3876,"referenced_errors":[{"created":"@1581123730.424381000","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":395,"grpc_status":14}]}"
>
2020-02-08 01:02:10,425 INFO download_runner.impl.historical_runner:32 sending - historical data request : A 2019-01-01 2020-01-01
2020-02-08 01:02:12,244 INFO download_runner.impl.historical_runner:35 sent - historical data request : A 2019-01-01 2020-01-01
2020-02-08 01:02:12,244 DEBUG download_runner.impl.historical_runner:36 request accounted for...
2020-02-08 01:02:12,244 INFO download_runner.impl.historical_runner:37 status : True
2020-02-08 01:02:12,244 INFO download_runner.impl.historical_runner:42 Historical data request sent : A 2019-01-01 2020-01-01
2020-02-08 01:02:12,244 DEBUG download_runner.impl.historical_end_reader:37 poll stock ? => True
2020-02-08 01:02:12,244 ERROR root:30 unhandled exception getting latest timestamp for AA
Traceback (most recent call last):
  File "/Users/dali/workspace/ib_python/runner/services/historical_data_service.py", line 24, in get_latest_timestamp
    response = self.stub.GetLatestTimeStamp(request)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 604, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 506, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1581123732.244592000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3876,"referenced_errors":[{"created":"@1581123732.244590000","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":395,"grpc_status":14}]}"
>
2020-02-08 01:02:12,244 INFO download_runner.impl.historical_runner:32 sending - historical data request : AA 2019-01-01 2020-01-01
2020-02-08 01:02:14,177 INFO download_runner.impl.historical_runner:35 sent - historical data request : AA 2019-01-01 2020-01-01
2020-02-08 01:02:14,177 DEBUG download_runner.impl.historical_runner:36 request accounted for...
2020-02-08 01:02:14,177 INFO download_runner.impl.historical_runner:37 status : True
2020-02-08 01:02:14,177 INFO download_runner.impl.historical_runner:42 Historical data request sent : AA 2019-01-01 2020-01-01
2020-02-08 01:02:14,177 DEBUG download_runner.impl.historical_end_reader:37 poll stock ? => True
2020-02-08 01:02:14,178 ERROR root:30 unhandled exception getting latest timestamp for AAAU
Traceback (most recent call last):
  File "/Users/dali/workspace/ib_python/runner/services/historical_data_service.py", line 24, in get_latest_timestamp
    response = self.stub.GetLatestTimeStamp(request)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 604, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 506, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1581123734.178244000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3876,"referenced_errors":[{"created":"@1581123734.178242000","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":395,"grpc_status":14}]}"
>
2020-02-08 01:02:14,178 INFO download_runner.impl.historical_runner:32 sending - historical data request : AAAU 2019-01-01 2020-01-01
2020-02-08 01:02:15,496 INFO download_runner.impl.historical_runner:35 sent - historical data request : AAAU 2019-01-01 2020-01-01
2020-02-08 01:02:15,496 DEBUG download_runner.impl.historical_runner:36 request accounted for...
2020-02-08 01:02:15,496 INFO download_runner.impl.historical_runner:37 status : True
2020-02-08 01:02:15,496 INFO download_runner.impl.historical_runner:42 Historical data request sent : AAAU 2019-01-01 2020-01-01
2020-02-08 01:02:15,497 DEBUG download_runner.impl.historical_end_reader:37 poll stock ? => True
2020-02-08 01:02:15,497 ERROR root:30 unhandled exception getting latest timestamp for AACG
Traceback (most recent call last):
  File "/Users/dali/workspace/ib_python/runner/services/historical_data_service.py", line 24, in get_latest_timestamp
    response = self.stub.GetLatestTimeStamp(request)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 604, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 506, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1581123735.497413000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3876,"referenced_errors":[{"created":"@1581123734.178242000","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":395,"grpc_status":14}]}"
>
2020-02-08 01:02:15,498 INFO download_runner.impl.historical_runner:32 sending - historical data request : AACG 2019-01-01 2020-01-01
2020-02-08 01:02:17,267 INFO download_runner.impl.historical_runner:35 sent - historical data request : AACG 2019-01-01 2020-01-01
2020-02-08 01:02:17,267 DEBUG download_runner.impl.historical_runner:36 request accounted for...
2020-02-08 01:02:17,267 INFO download_runner.impl.historical_runner:37 status : True
2020-02-08 01:02:17,267 INFO download_runner.impl.historical_runner:42 Historical data request sent : AACG 2019-01-01 2020-01-01
2020-02-08 01:02:17,267 DEBUG download_runner.impl.historical_end_reader:37 poll stock ? => True
2020-02-08 01:02:17,267 ERROR root:30 unhandled exception getting latest timestamp for AADR
Traceback (most recent call last):
  File "/Users/dali/workspace/ib_python/runner/services/historical_data_service.py", line 24, in get_latest_timestamp
    response = self.stub.GetLatestTimeStamp(request)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 604, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 506, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1581123737.267787000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3876,"referenced_errors":[{"created":"@1581123734.178242000","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":395,"grpc_status":14}]}"
>
2020-02-08 01:02:17,268 INFO download_runner.impl.historical_runner:32 sending - historical data request : AADR 2019-01-01 2020-01-01
