2020-02-07 17:19:17,550 DEBUG download_runner.impl.historical_end_reader:37 poll stock ? => True
2020-02-07 17:19:17,678 ERROR root:30 unhandled exception getting latest timestamp for AEE
Traceback (most recent call last):
  File "/Users/dali/workspace/ib_python/runner/services/historical_data_service.py", line 24, in get_latest_timestamp
    response = self.stub.GetLatestTimeStamp(request)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 604, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 506, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1581095957.678735000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3876,"referenced_errors":[{"created":"@1581095957.678734000","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":395,"grpc_status":14}]}"
>
2020-02-07 17:19:17,680 INFO download_runner.impl.historical_runner:32 sending - historical data request : AEE 2019-01-01 2020-01-01
2020-02-07 17:19:18,012 INFO download_runner.impl.historical_runner:35 sent - historical data request : AEE 2019-01-01 2020-01-01
2020-02-07 17:19:18,012 DEBUG download_runner.impl.historical_runner:36 request accounted for...
2020-02-07 17:19:18,012 INFO download_runner.impl.historical_runner:37 status : True
2020-02-07 17:19:18,012 INFO download_runner.impl.historical_runner:42 Historical data request sent : AEE 2019-01-01 2020-01-01
2020-02-07 17:19:18,012 DEBUG download_runner.impl.historical_end_reader:37 poll stock ? => True
2020-02-07 17:19:18,012 ERROR root:30 unhandled exception getting latest timestamp for A
Traceback (most recent call last):
  File "/Users/dali/workspace/ib_python/runner/services/historical_data_service.py", line 24, in get_latest_timestamp
    response = self.stub.GetLatestTimeStamp(request)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 604, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 506, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1581095958.012706000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3876,"referenced_errors":[{"created":"@1581095957.678734000","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":395,"grpc_status":14}]}"
>
2020-02-07 17:19:18,013 INFO download_runner.impl.historical_runner:32 sending - historical data request : A 2019-01-01 2020-01-01
2020-02-07 17:19:18,477 INFO download_runner.impl.historical_runner:35 sent - historical data request : A 2019-01-01 2020-01-01
2020-02-07 17:19:18,477 DEBUG download_runner.impl.historical_runner:36 request accounted for...
2020-02-07 17:19:18,477 INFO download_runner.impl.historical_runner:37 status : True
2020-02-07 17:19:18,477 INFO download_runner.impl.historical_runner:42 Historical data request sent : A 2019-01-01 2020-01-01
2020-02-07 17:19:18,477 DEBUG download_runner.impl.historical_end_reader:37 poll stock ? => True
2020-02-07 17:19:18,478 ERROR root:30 unhandled exception getting latest timestamp for AA
Traceback (most recent call last):
  File "/Users/dali/workspace/ib_python/runner/services/historical_data_service.py", line 24, in get_latest_timestamp
    response = self.stub.GetLatestTimeStamp(request)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 604, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 506, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1581095958.478156000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3876,"referenced_errors":[{"created":"@1581095957.678734000","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":395,"grpc_status":14}]}"
>
2020-02-07 17:19:18,478 INFO download_runner.impl.historical_runner:32 sending - historical data request : AA 2019-01-01 2020-01-01
2020-02-07 17:19:19,446 INFO download_runner.impl.historical_runner:35 sent - historical data request : AA 2019-01-01 2020-01-01
2020-02-07 17:19:19,446 DEBUG download_runner.impl.historical_runner:36 request accounted for...
2020-02-07 17:19:19,446 INFO download_runner.impl.historical_runner:37 status : True
2020-02-07 17:19:19,446 INFO download_runner.impl.historical_runner:42 Historical data request sent : AA 2019-01-01 2020-01-01
2020-02-07 17:19:19,446 DEBUG download_runner.impl.historical_end_reader:37 poll stock ? => True
2020-02-07 17:19:19,446 ERROR root:30 unhandled exception getting latest timestamp for AAAU
Traceback (most recent call last):
  File "/Users/dali/workspace/ib_python/runner/services/historical_data_service.py", line 24, in get_latest_timestamp
    response = self.stub.GetLatestTimeStamp(request)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 604, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 506, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1581095959.446546000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3876,"referenced_errors":[{"created":"@1581095959.446544000","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":395,"grpc_status":14}]}"
>
2020-02-07 17:19:19,446 INFO download_runner.impl.historical_runner:32 sending - historical data request : AAAU 2019-01-01 2020-01-01
2020-02-07 17:19:20,122 INFO download_runner.impl.historical_runner:35 sent - historical data request : AAAU 2019-01-01 2020-01-01
2020-02-07 17:19:20,122 DEBUG download_runner.impl.historical_runner:36 request accounted for...
2020-02-07 17:19:20,122 INFO download_runner.impl.historical_runner:37 status : True
2020-02-07 17:19:20,122 INFO download_runner.impl.historical_runner:42 Historical data request sent : AAAU 2019-01-01 2020-01-01
2020-02-07 17:19:20,122 DEBUG download_runner.impl.historical_end_reader:37 poll stock ? => True
2020-02-07 17:19:20,122 ERROR root:30 unhandled exception getting latest timestamp for AACG
Traceback (most recent call last):
  File "/Users/dali/workspace/ib_python/runner/services/historical_data_service.py", line 24, in get_latest_timestamp
    response = self.stub.GetLatestTimeStamp(request)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 604, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 506, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1581095960.122805000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3876,"referenced_errors":[{"created":"@1581095959.446544000","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":395,"grpc_status":14}]}"
>
2020-02-07 17:19:20,123 INFO download_runner.impl.historical_runner:32 sending - historical data request : AACG 2019-01-01 2020-01-01
2020-02-07 17:19:20,961 INFO download_runner.impl.historical_runner:35 sent - historical data request : AACG 2019-01-01 2020-01-01
2020-02-07 17:19:20,961 DEBUG download_runner.impl.historical_runner:36 request accounted for...
2020-02-07 17:19:20,961 INFO download_runner.impl.historical_runner:37 status : True
2020-02-07 17:19:20,962 INFO download_runner.impl.historical_runner:42 Historical data request sent : AACG 2019-01-01 2020-01-01
2020-02-07 17:19:20,962 DEBUG download_runner.impl.historical_end_reader:37 poll stock ? => True
2020-02-07 17:19:20,962 ERROR root:30 unhandled exception getting latest timestamp for AADR
Traceback (most recent call last):
  File "/Users/dali/workspace/ib_python/runner/services/historical_data_service.py", line 24, in get_latest_timestamp
    response = self.stub.GetLatestTimeStamp(request)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 604, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 506, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1581095960.962344000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3876,"referenced_errors":[{"created":"@1581095960.962342000","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":395,"grpc_status":14}]}"
>
2020-02-07 17:19:20,962 INFO download_runner.impl.historical_runner:32 sending - historical data request : AADR 2019-01-01 2020-01-01
2020-02-07 17:19:24,287 INFO download_runner.impl.historical_runner:35 sent - historical data request : AADR 2019-01-01 2020-01-01
2020-02-07 17:19:24,288 DEBUG download_runner.impl.historical_runner:36 request accounted for...
2020-02-07 17:19:24,288 INFO download_runner.impl.historical_runner:37 status : True
2020-02-07 17:19:24,288 INFO download_runner.impl.historical_runner:42 Historical data request sent : AADR 2019-01-01 2020-01-01
2020-02-07 17:19:24,288 DEBUG download_runner.impl.historical_end_reader:37 poll stock ? => True
2020-02-07 17:19:24,288 ERROR root:30 unhandled exception getting latest timestamp for AAL
Traceback (most recent call last):
  File "/Users/dali/workspace/ib_python/runner/services/historical_data_service.py", line 24, in get_latest_timestamp
    response = self.stub.GetLatestTimeStamp(request)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 604, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 506, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1581095964.288566000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3876,"referenced_errors":[{"created":"@1581095964.288565000","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":395,"grpc_status":14}]}"
>
2020-02-07 17:19:24,289 INFO download_runner.impl.historical_runner:32 sending - historical data request : AAL 2019-01-01 2020-01-01
2020-02-07 17:19:24,480 INFO download_runner.impl.historical_runner:35 sent - historical data request : AAL 2019-01-01 2020-01-01
2020-02-07 17:19:24,480 DEBUG download_runner.impl.historical_runner:36 request accounted for...
2020-02-07 17:19:24,480 INFO download_runner.impl.historical_runner:37 status : True
2020-02-07 17:19:24,480 INFO download_runner.impl.historical_runner:42 Historical data request sent : AAL 2019-01-01 2020-01-01
2020-02-07 17:19:24,480 DEBUG download_runner.impl.historical_end_reader:37 poll stock ? => True
2020-02-07 17:19:24,481 ERROR root:30 unhandled exception getting latest timestamp for AAMC
Traceback (most recent call last):
  File "/Users/dali/workspace/ib_python/runner/services/historical_data_service.py", line 24, in get_latest_timestamp
    response = self.stub.GetLatestTimeStamp(request)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 604, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 506, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1581095964.481170000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3876,"referenced_errors":[{"created":"@1581095964.288565000","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":395,"grpc_status":14}]}"
>
2020-02-07 17:19:24,481 INFO download_runner.impl.historical_runner:32 sending - historical data request : AAMC 2019-01-01 2020-01-01
2020-02-07 17:19:25,262 INFO download_runner.impl.historical_runner:35 sent - historical data request : AAMC 2019-01-01 2020-01-01
2020-02-07 17:19:25,262 DEBUG download_runner.impl.historical_runner:36 request accounted for...
2020-02-07 17:19:25,262 INFO download_runner.impl.historical_runner:37 status : True
2020-02-07 17:19:25,262 INFO download_runner.impl.historical_runner:42 Historical data request sent : AAMC 2019-01-01 2020-01-01
2020-02-07 17:19:25,262 DEBUG download_runner.impl.historical_end_reader:37 poll stock ? => True
2020-02-07 17:19:25,262 ERROR root:30 unhandled exception getting latest timestamp for AAME
Traceback (most recent call last):
  File "/Users/dali/workspace/ib_python/runner/services/historical_data_service.py", line 24, in get_latest_timestamp
    response = self.stub.GetLatestTimeStamp(request)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 604, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 506, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1581095965.262643000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3876,"referenced_errors":[{"created":"@1581095964.288565000","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":395,"grpc_status":14}]}"
>
2020-02-07 17:19:25,263 INFO download_runner.impl.historical_runner:32 sending - historical data request : AAME 2019-01-01 2020-01-01
2020-02-07 17:19:30,306 INFO download_runner.impl.historical_runner:35 sent - historical data request : AAME 2019-01-01 2020-01-01
2020-02-07 17:19:30,307 DEBUG download_runner.impl.historical_runner:36 request accounted for...
2020-02-07 17:19:30,307 INFO download_runner.impl.historical_runner:37 status : True
2020-02-07 17:19:30,307 INFO download_runner.impl.historical_runner:42 Historical data request sent : AAME 2019-01-01 2020-01-01
2020-02-07 17:19:30,307 DEBUG download_runner.impl.historical_end_reader:37 poll stock ? => True
2020-02-07 17:19:30,308 ERROR root:30 unhandled exception getting latest timestamp for AAN
Traceback (most recent call last):
  File "/Users/dali/workspace/ib_python/runner/services/historical_data_service.py", line 24, in get_latest_timestamp
    response = self.stub.GetLatestTimeStamp(request)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 604, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 506, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1581095970.308718000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3876,"referenced_errors":[{"created":"@1581095967.552896000","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":395,"grpc_status":14}]}"
>
2020-02-07 17:19:30,309 INFO download_runner.impl.historical_runner:32 sending - historical data request : AAN 2019-01-01 2020-01-01
2020-02-07 17:19:30,756 INFO download_runner.impl.historical_runner:35 sent - historical data request : AAN 2019-01-01 2020-01-01
2020-02-07 17:19:30,756 DEBUG download_runner.impl.historical_runner:36 request accounted for...
2020-02-07 17:19:30,757 INFO download_runner.impl.historical_runner:37 status : True
2020-02-07 17:19:30,757 INFO download_runner.impl.historical_runner:42 Historical data request sent : AAN 2019-01-01 2020-01-01
2020-02-07 17:19:30,757 DEBUG download_runner.impl.historical_end_reader:37 poll stock ? => True
2020-02-07 17:19:30,758 ERROR root:30 unhandled exception getting latest timestamp for AAOI
Traceback (most recent call last):
  File "/Users/dali/workspace/ib_python/runner/services/historical_data_service.py", line 24, in get_latest_timestamp
    response = self.stub.GetLatestTimeStamp(request)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 604, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 506, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1581095970.758325000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3876,"referenced_errors":[{"created":"@1581095967.552896000","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":395,"grpc_status":14}]}"
>
2020-02-07 17:19:30,759 INFO download_runner.impl.historical_runner:32 sending - historical data request : AAOI 2019-01-01 2020-01-01
2020-02-07 17:19:31,353 INFO download_runner.impl.historical_runner:35 sent - historical data request : AAOI 2019-01-01 2020-01-01
2020-02-07 17:19:31,353 DEBUG download_runner.impl.historical_runner:36 request accounted for...
2020-02-07 17:19:31,353 INFO download_runner.impl.historical_runner:37 status : True
2020-02-07 17:19:31,353 INFO download_runner.impl.historical_runner:42 Historical data request sent : AAOI 2019-01-01 2020-01-01
2020-02-07 17:19:31,353 DEBUG download_runner.impl.historical_end_reader:37 poll stock ? => True
2020-02-07 17:19:31,353 ERROR root:30 unhandled exception getting latest timestamp for AAON
Traceback (most recent call last):
  File "/Users/dali/workspace/ib_python/runner/services/historical_data_service.py", line 24, in get_latest_timestamp
    response = self.stub.GetLatestTimeStamp(request)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 604, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 506, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1581095971.353687000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3876,"referenced_errors":[{"created":"@1581095967.552896000","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":395,"grpc_status":14}]}"
>
2020-02-07 17:19:31,354 INFO download_runner.impl.historical_runner:32 sending - historical data request : AAON 2019-01-01 2020-01-01
2020-02-07 17:19:36,407 INFO download_runner.impl.historical_runner:35 sent - historical data request : AAON 2019-01-01 2020-01-01
2020-02-07 17:19:36,407 DEBUG download_runner.impl.historical_runner:36 request accounted for...
2020-02-07 17:19:36,407 INFO download_runner.impl.historical_runner:37 status : True
2020-02-07 17:19:36,407 INFO download_runner.impl.historical_runner:42 Historical data request sent : AAON 2019-01-01 2020-01-01
2020-02-07 17:19:36,407 DEBUG download_runner.impl.historical_end_reader:37 poll stock ? => True
2020-02-07 17:19:36,408 ERROR root:30 unhandled exception getting latest timestamp for AAP
Traceback (most recent call last):
  File "/Users/dali/workspace/ib_python/runner/services/historical_data_service.py", line 24, in get_latest_timestamp
    response = self.stub.GetLatestTimeStamp(request)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 604, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 506, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1581095976.408715000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3876,"referenced_errors":[{"created":"@1581095976.408713000","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":395,"grpc_status":14}]}"
>
2020-02-07 17:19:36,409 INFO download_runner.impl.historical_runner:32 sending - historical data request : AAP 2019-01-01 2020-01-01
2020-02-07 17:19:42,454 INFO download_runner.impl.historical_runner:35 sent - historical data request : AAP 2019-01-01 2020-01-01
2020-02-07 17:19:42,454 DEBUG download_runner.impl.historical_runner:36 request accounted for...
2020-02-07 17:19:42,455 INFO download_runner.impl.historical_runner:37 status : True
2020-02-07 17:19:42,455 INFO download_runner.impl.historical_runner:42 Historical data request sent : AAP 2019-01-01 2020-01-01
2020-02-07 17:19:42,455 DEBUG download_runner.impl.historical_end_reader:37 poll stock ? => True
2020-02-07 17:19:42,455 ERROR root:30 unhandled exception getting latest timestamp for AAPL
Traceback (most recent call last):
  File "/Users/dali/workspace/ib_python/runner/services/historical_data_service.py", line 24, in get_latest_timestamp
    response = self.stub.GetLatestTimeStamp(request)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 604, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 506, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1581095982.455556000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3876,"referenced_errors":[{"created":"@1581095976.408713000","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":395,"grpc_status":14}]}"
>
2020-02-07 17:19:42,456 INFO download_runner.impl.historical_runner:32 sending - historical data request : AAPL 2019-01-01 2020-01-01
2020-02-07 17:19:42,679 INFO download_runner.impl.historical_runner:35 sent - historical data request : AAPL 2019-01-01 2020-01-01
2020-02-07 17:19:42,679 DEBUG download_runner.impl.historical_runner:36 request accounted for...
2020-02-07 17:19:42,679 INFO download_runner.impl.historical_runner:37 status : True
2020-02-07 17:19:42,679 INFO download_runner.impl.historical_runner:42 Historical data request sent : AAPL 2019-01-01 2020-01-01
2020-02-07 17:19:42,679 DEBUG download_runner.impl.historical_end_reader:37 poll stock ? => True
2020-02-07 17:19:42,679 ERROR root:30 unhandled exception getting latest timestamp for AAT
Traceback (most recent call last):
  File "/Users/dali/workspace/ib_python/runner/services/historical_data_service.py", line 24, in get_latest_timestamp
    response = self.stub.GetLatestTimeStamp(request)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 604, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 506, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1581095982.679788000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3876,"referenced_errors":[{"created":"@1581095976.408713000","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":395,"grpc_status":14}]}"
>
2020-02-07 17:19:42,680 INFO download_runner.impl.historical_runner:32 sending - historical data request : AAT 2019-01-01 2020-01-01
2020-02-07 17:19:42,828 INFO download_runner.impl.historical_runner:35 sent - historical data request : AAT 2019-01-01 2020-01-01
2020-02-07 17:19:42,828 DEBUG download_runner.impl.historical_runner:36 request accounted for...
2020-02-07 17:19:42,828 INFO download_runner.impl.historical_runner:37 status : True
2020-02-07 17:19:42,829 INFO download_runner.impl.historical_runner:42 Historical data request sent : AAT 2019-01-01 2020-01-01
2020-02-07 17:19:42,829 DEBUG download_runner.impl.historical_end_reader:37 poll stock ? => True
2020-02-07 17:19:42,829 ERROR root:30 unhandled exception getting latest timestamp for AAU
Traceback (most recent call last):
  File "/Users/dali/workspace/ib_python/runner/services/historical_data_service.py", line 24, in get_latest_timestamp
    response = self.stub.GetLatestTimeStamp(request)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 604, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 506, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1581095982.829358000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3876,"referenced_errors":[{"created":"@1581095976.408713000","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":395,"grpc_status":14}]}"
>
2020-02-07 17:19:42,829 INFO download_runner.impl.historical_runner:32 sending - historical data request : AAU 2019-01-01 2020-01-01
2020-02-07 17:19:48,356 INFO download_runner.impl.historical_runner:35 sent - historical data request : AAU 2019-01-01 2020-01-01
2020-02-07 17:19:48,357 DEBUG download_runner.impl.historical_runner:36 request accounted for...
2020-02-07 17:19:48,357 INFO download_runner.impl.historical_runner:37 status : True
2020-02-07 17:19:48,358 INFO download_runner.impl.historical_runner:42 Historical data request sent : AAU 2019-01-01 2020-01-01
2020-02-07 17:19:48,359 DEBUG download_runner.impl.historical_end_reader:37 poll stock ? => True
2020-02-07 17:19:48,362 ERROR root:30 unhandled exception getting latest timestamp for AAWW
Traceback (most recent call last):
  File "/Users/dali/workspace/ib_python/runner/services/historical_data_service.py", line 24, in get_latest_timestamp
    response = self.stub.GetLatestTimeStamp(request)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 604, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 506, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1581095988.361802000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3876,"referenced_errors":[{"created":"@1581095987.563552000","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":395,"grpc_status":14}]}"
>
2020-02-07 17:19:48,362 INFO download_runner.impl.historical_runner:32 sending - historical data request : AAWW 2019-01-01 2020-01-01
2020-02-07 17:19:48,535 INFO download_runner.impl.historical_runner:35 sent - historical data request : AAWW 2019-01-01 2020-01-01
2020-02-07 17:19:48,536 DEBUG download_runner.impl.historical_runner:36 request accounted for...
2020-02-07 17:19:48,536 INFO download_runner.impl.historical_runner:37 status : True
2020-02-07 17:19:48,536 INFO download_runner.impl.historical_runner:42 Historical data request sent : AAWW 2019-01-01 2020-01-01
2020-02-07 17:19:48,536 DEBUG download_runner.impl.historical_end_reader:37 poll stock ? => True
2020-02-07 17:19:48,536 ERROR root:30 unhandled exception getting latest timestamp for AAXJ
Traceback (most recent call last):
  File "/Users/dali/workspace/ib_python/runner/services/historical_data_service.py", line 24, in get_latest_timestamp
    response = self.stub.GetLatestTimeStamp(request)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 604, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 506, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1581095988.536461000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3876,"referenced_errors":[{"created":"@1581095987.563552000","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":395,"grpc_status":14}]}"
>
2020-02-07 17:19:48,536 INFO download_runner.impl.historical_runner:32 sending - historical data request : AAXJ 2019-01-01 2020-01-01
