2020-02-08 13:57:01,393 DEBUG download_runner.impl.historical_end_reader:37 poll stock ? => True
2020-02-08 13:57:01,590 ERROR root:30 unhandled exception getting latest timestamp for A
Traceback (most recent call last):
  File "/Users/dali/workspace/ib_python/runner/services/historical_data_service.py", line 24, in get_latest_timestamp
    response = self.stub.GetLatestTimeStamp(request)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 604, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 506, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1581170221.590188000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3876,"referenced_errors":[{"created":"@1581170221.590187000","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":395,"grpc_status":14}]}"
>
2020-02-08 13:57:01,591 INFO download_runner.impl.historical_runner:32 sending - historical data request : A 2019-12-01 2020-01-01
2020-02-08 13:57:02,909 INFO download_runner.impl.historical_runner:35 sent - historical data request : A 2019-12-01 2020-01-01
2020-02-08 13:57:02,909 DEBUG download_runner.impl.historical_runner:36 request accounted for...
2020-02-08 13:57:02,909 INFO download_runner.impl.historical_runner:37 status : True
2020-02-08 13:57:02,909 INFO download_runner.impl.historical_runner:42 Historical data request sent : A 2019-12-01 2020-01-01
2020-02-08 13:57:02,909 DEBUG download_runner.impl.historical_end_reader:37 poll stock ? => True
2020-02-08 13:57:02,910 ERROR root:30 unhandled exception getting latest timestamp for ACIA
Traceback (most recent call last):
  File "/Users/dali/workspace/ib_python/runner/services/historical_data_service.py", line 24, in get_latest_timestamp
    response = self.stub.GetLatestTimeStamp(request)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 604, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 506, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1581170222.910030000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3876,"referenced_errors":[{"created":"@1581170222.910028000","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":395,"grpc_status":14}]}"
>
2020-02-08 13:57:02,910 INFO download_runner.impl.historical_runner:32 sending - historical data request : ACIA 2019-12-01 2020-01-01
2020-02-08 13:57:04,126 INFO download_runner.impl.historical_runner:35 sent - historical data request : ACIA 2019-12-01 2020-01-01
2020-02-08 13:57:04,127 DEBUG download_runner.impl.historical_runner:36 request accounted for...
2020-02-08 13:57:04,127 INFO download_runner.impl.historical_runner:37 status : True
2020-02-08 13:57:04,127 INFO download_runner.impl.historical_runner:42 Historical data request sent : ACIA 2019-12-01 2020-01-01
2020-02-08 13:57:04,127 DEBUG download_runner.impl.historical_end_reader:37 poll stock ? => True
2020-02-08 13:57:04,127 ERROR root:30 unhandled exception getting latest timestamp for ACIO
Traceback (most recent call last):
  File "/Users/dali/workspace/ib_python/runner/services/historical_data_service.py", line 24, in get_latest_timestamp
    response = self.stub.GetLatestTimeStamp(request)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 604, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 506, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1581170224.127448000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3876,"referenced_errors":[{"created":"@1581170222.910028000","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":395,"grpc_status":14}]}"
>
2020-02-08 13:57:04,127 INFO download_runner.impl.historical_runner:32 sending - historical data request : ACIO 2019-12-01 2020-01-01
2020-02-08 13:57:05,295 INFO download_runner.impl.historical_runner:35 sent - historical data request : ACIO 2019-12-01 2020-01-01
2020-02-08 13:57:05,295 DEBUG download_runner.impl.historical_runner:36 request accounted for...
2020-02-08 13:57:05,295 INFO download_runner.impl.historical_runner:37 status : True
2020-02-08 13:57:05,295 INFO download_runner.impl.historical_runner:42 Historical data request sent : ACIO 2019-12-01 2020-01-01
2020-02-08 13:57:05,295 DEBUG download_runner.impl.historical_end_reader:37 poll stock ? => True
2020-02-08 13:57:05,295 ERROR root:30 unhandled exception getting latest timestamp for ACIU
Traceback (most recent call last):
  File "/Users/dali/workspace/ib_python/runner/services/historical_data_service.py", line 24, in get_latest_timestamp
    response = self.stub.GetLatestTimeStamp(request)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 604, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 506, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1581170225.295908000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3876,"referenced_errors":[{"created":"@1581170225.295907000","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":395,"grpc_status":14}]}"
>
2020-02-08 13:57:05,296 INFO download_runner.impl.historical_runner:32 sending - historical data request : ACIU 2019-12-01 2020-01-01
2020-02-08 13:57:06,500 INFO download_runner.impl.historical_runner:35 sent - historical data request : ACIU 2019-12-01 2020-01-01
2020-02-08 13:57:06,500 DEBUG download_runner.impl.historical_runner:36 request accounted for...
2020-02-08 13:57:06,500 INFO download_runner.impl.historical_runner:37 status : True
2020-02-08 13:57:06,500 INFO download_runner.impl.historical_runner:42 Historical data request sent : ACIU 2019-12-01 2020-01-01
2020-02-08 13:57:06,500 DEBUG download_runner.impl.historical_end_reader:37 poll stock ? => True
2020-02-08 13:57:06,500 ERROR root:30 unhandled exception getting latest timestamp for ACIW
Traceback (most recent call last):
  File "/Users/dali/workspace/ib_python/runner/services/historical_data_service.py", line 24, in get_latest_timestamp
    response = self.stub.GetLatestTimeStamp(request)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 604, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 506, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1581170226.500547000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3876,"referenced_errors":[{"created":"@1581170225.295907000","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":395,"grpc_status":14}]}"
>
2020-02-08 13:57:06,500 INFO download_runner.impl.historical_runner:32 sending - historical data request : ACIW 2019-12-01 2020-01-01
2020-02-08 13:57:07,640 INFO download_runner.impl.historical_runner:35 sent - historical data request : ACIW 2019-12-01 2020-01-01
2020-02-08 13:57:07,640 DEBUG download_runner.impl.historical_runner:36 request accounted for...
2020-02-08 13:57:07,640 INFO download_runner.impl.historical_runner:37 status : True
2020-02-08 13:57:07,640 INFO download_runner.impl.historical_runner:42 Historical data request sent : ACIW 2019-12-01 2020-01-01
2020-02-08 13:57:07,640 DEBUG download_runner.impl.historical_end_reader:37 poll stock ? => True
2020-02-08 13:57:07,640 ERROR root:30 unhandled exception getting latest timestamp for ACLS
Traceback (most recent call last):
  File "/Users/dali/workspace/ib_python/runner/services/historical_data_service.py", line 24, in get_latest_timestamp
    response = self.stub.GetLatestTimeStamp(request)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 604, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 506, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1581170227.640895000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3876,"referenced_errors":[{"created":"@1581170227.640893000","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":395,"grpc_status":14}]}"
>
2020-02-08 13:57:07,641 INFO download_runner.impl.historical_runner:32 sending - historical data request : ACLS 2019-12-01 2020-01-01
2020-02-08 13:57:08,890 INFO download_runner.impl.historical_runner:35 sent - historical data request : ACLS 2019-12-01 2020-01-01
2020-02-08 13:57:08,890 DEBUG download_runner.impl.historical_runner:36 request accounted for...
2020-02-08 13:57:08,890 INFO download_runner.impl.historical_runner:37 status : True
2020-02-08 13:57:08,890 INFO download_runner.impl.historical_runner:42 Historical data request sent : ACLS 2019-12-01 2020-01-01
2020-02-08 13:57:08,890 DEBUG download_runner.impl.historical_end_reader:37 poll stock ? => True
2020-02-08 13:57:08,890 ERROR root:30 unhandled exception getting latest timestamp for ACM
Traceback (most recent call last):
  File "/Users/dali/workspace/ib_python/runner/services/historical_data_service.py", line 24, in get_latest_timestamp
    response = self.stub.GetLatestTimeStamp(request)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 604, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 506, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1581170228.890681000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3876,"referenced_errors":[{"created":"@1581170227.640893000","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":395,"grpc_status":14}]}"
>
2020-02-08 13:57:08,891 INFO download_runner.impl.historical_runner:32 sending - historical data request : ACM 2019-12-01 2020-01-01
2020-02-08 13:57:10,365 INFO download_runner.impl.historical_runner:35 sent - historical data request : ACM 2019-12-01 2020-01-01
2020-02-08 13:57:10,366 DEBUG download_runner.impl.historical_runner:36 request accounted for...
2020-02-08 13:57:10,366 INFO download_runner.impl.historical_runner:37 status : True
2020-02-08 13:57:10,366 INFO download_runner.impl.historical_runner:42 Historical data request sent : ACM 2019-12-01 2020-01-01
2020-02-08 13:57:10,366 DEBUG download_runner.impl.historical_end_reader:37 poll stock ? => True
2020-02-08 13:57:10,367 ERROR root:30 unhandled exception getting latest timestamp for ACMR
Traceback (most recent call last):
  File "/Users/dali/workspace/ib_python/runner/services/historical_data_service.py", line 24, in get_latest_timestamp
    response = self.stub.GetLatestTimeStamp(request)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 604, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 506, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1581170230.367273000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3876,"referenced_errors":[{"created":"@1581170227.640893000","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":395,"grpc_status":14}]}"
>
2020-02-08 13:57:10,368 INFO download_runner.impl.historical_runner:32 sending - historical data request : ACMR 2019-12-01 2020-01-01
2020-02-08 13:57:11,614 INFO download_runner.impl.historical_runner:35 sent - historical data request : ACMR 2019-12-01 2020-01-01
2020-02-08 13:57:11,614 DEBUG download_runner.impl.historical_runner:36 request accounted for...
2020-02-08 13:57:11,614 INFO download_runner.impl.historical_runner:37 status : True
2020-02-08 13:57:11,614 INFO download_runner.impl.historical_runner:42 Historical data request sent : ACMR 2019-12-01 2020-01-01
2020-02-08 13:57:11,614 DEBUG download_runner.impl.historical_end_reader:37 poll stock ? => True
2020-02-08 13:57:11,615 ERROR root:30 unhandled exception getting latest timestamp for ACN
Traceback (most recent call last):
  File "/Users/dali/workspace/ib_python/runner/services/historical_data_service.py", line 24, in get_latest_timestamp
    response = self.stub.GetLatestTimeStamp(request)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 604, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 506, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1581170231.615004000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3876,"referenced_errors":[{"created":"@1581170231.397688000","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":395,"grpc_status":14}]}"
>
2020-02-08 13:57:11,615 INFO download_runner.impl.historical_runner:32 sending - historical data request : ACN 2019-12-01 2020-01-01
2020-02-08 13:57:13,060 INFO download_runner.impl.historical_runner:35 sent - historical data request : ACN 2019-12-01 2020-01-01
2020-02-08 13:57:13,061 DEBUG download_runner.impl.historical_runner:36 request accounted for...
2020-02-08 13:57:13,061 INFO download_runner.impl.historical_runner:37 status : True
2020-02-08 13:57:13,061 INFO download_runner.impl.historical_runner:42 Historical data request sent : ACN 2019-12-01 2020-01-01
2020-02-08 13:57:13,061 DEBUG download_runner.impl.historical_end_reader:37 poll stock ? => True
2020-02-08 13:57:13,061 ERROR root:30 unhandled exception getting latest timestamp for ACNB
Traceback (most recent call last):
  File "/Users/dali/workspace/ib_python/runner/services/historical_data_service.py", line 24, in get_latest_timestamp
    response = self.stub.GetLatestTimeStamp(request)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 604, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 506, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1581170233.061380000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3876,"referenced_errors":[{"created":"@1581170231.397688000","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":395,"grpc_status":14}]}"
>
2020-02-08 13:57:13,061 INFO download_runner.impl.historical_runner:32 sending - historical data request : ACNB 2019-12-01 2020-01-01
2020-02-08 13:57:46,591 INFO download_runner.impl.historical_runner:35 sent - historical data request : ACNB 2019-12-01 2020-01-01
2020-02-08 13:57:46,591 DEBUG download_runner.impl.historical_runner:36 request accounted for...
2020-02-08 13:57:46,591 INFO download_runner.impl.historical_runner:37 status : True
2020-02-08 13:57:46,591 INFO download_runner.impl.historical_runner:42 Historical data request sent : ACNB 2019-12-01 2020-01-01
2020-02-08 13:57:46,591 DEBUG download_runner.impl.historical_end_reader:37 poll stock ? => True
2020-02-08 13:57:46,592 ERROR root:30 unhandled exception getting latest timestamp for ACOR
Traceback (most recent call last):
  File "/Users/dali/workspace/ib_python/runner/services/historical_data_service.py", line 24, in get_latest_timestamp
    response = self.stub.GetLatestTimeStamp(request)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 604, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 506, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1581170266.592088000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3876,"referenced_errors":[{"created":"@1581170266.419929000","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":395,"grpc_status":14}]}"
>
2020-02-08 13:57:46,592 INFO download_runner.impl.historical_runner:32 sending - historical data request : ACOR 2019-12-01 2020-01-01
2020-02-08 13:57:50,565 INFO download_runner.impl.historical_runner:35 sent - historical data request : ACOR 2019-12-01 2020-01-01
2020-02-08 13:57:50,565 DEBUG download_runner.impl.historical_runner:36 request accounted for...
2020-02-08 13:57:50,565 INFO download_runner.impl.historical_runner:37 status : True
2020-02-08 13:57:50,565 INFO download_runner.impl.historical_runner:42 Historical data request sent : ACOR 2019-12-01 2020-01-01
2020-02-08 13:57:50,565 DEBUG download_runner.impl.historical_end_reader:37 poll stock ? => True
2020-02-08 13:57:50,565 ERROR root:30 unhandled exception getting latest timestamp for ACP
Traceback (most recent call last):
  File "/Users/dali/workspace/ib_python/runner/services/historical_data_service.py", line 24, in get_latest_timestamp
    response = self.stub.GetLatestTimeStamp(request)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 604, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 506, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1581170270.565917000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3876,"referenced_errors":[{"created":"@1581170266.419929000","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":395,"grpc_status":14}]}"
>
2020-02-08 13:57:50,566 INFO download_runner.impl.historical_runner:32 sending - historical data request : ACP 2019-12-01 2020-01-01
