2020-02-08 12:44:22,576 DEBUG download_runner.impl.historical_end_reader:37 poll stock ? => True
2020-02-08 12:44:22,708 ERROR root:30 unhandled exception getting latest timestamp for ACIA
Traceback (most recent call last):
  File "/Users/dali/workspace/ib_python/runner/services/historical_data_service.py", line 24, in get_latest_timestamp
    response = self.stub.GetLatestTimeStamp(request)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 604, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 506, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1581165862.707967000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3876,"referenced_errors":[{"created":"@1581165862.707966000","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":395,"grpc_status":14}]}"
>
2020-02-08 12:44:22,709 INFO download_runner.impl.historical_runner:32 sending - historical data request : ACIA 2019-01-01 2020-01-01
2020-02-08 12:44:36,777 INFO download_runner.impl.historical_runner:35 sent - historical data request : ACIA 2019-01-01 2020-01-01
2020-02-08 12:44:36,778 DEBUG download_runner.impl.historical_runner:36 request accounted for...
2020-02-08 12:44:36,778 INFO download_runner.impl.historical_runner:37 status : True
2020-02-08 12:44:36,778 INFO download_runner.impl.historical_runner:42 Historical data request sent : ACIA 2019-01-01 2020-01-01
2020-02-08 12:44:36,778 DEBUG download_runner.impl.historical_end_reader:37 poll stock ? => True
2020-02-08 12:44:36,778 ERROR root:30 unhandled exception getting latest timestamp for A
Traceback (most recent call last):
  File "/Users/dali/workspace/ib_python/runner/services/historical_data_service.py", line 24, in get_latest_timestamp
    response = self.stub.GetLatestTimeStamp(request)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 604, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 506, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1581165876.778442000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3876,"referenced_errors":[{"created":"@1581165876.778441000","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":395,"grpc_status":14}]}"
>
2020-02-08 12:44:36,778 INFO download_runner.impl.historical_runner:32 sending - historical data request : A 2019-01-01 2020-01-01
2020-02-08 12:44:39,541 INFO download_runner.impl.historical_runner:35 sent - historical data request : A 2019-01-01 2020-01-01
2020-02-08 12:44:39,541 DEBUG download_runner.impl.historical_runner:36 request accounted for...
2020-02-08 12:44:39,541 INFO download_runner.impl.historical_runner:37 status : True
2020-02-08 12:44:39,541 INFO download_runner.impl.historical_runner:42 Historical data request sent : A 2019-01-01 2020-01-01
2020-02-08 12:44:39,541 DEBUG download_runner.impl.historical_end_reader:37 poll stock ? => True
2020-02-08 12:44:39,542 ERROR root:30 unhandled exception getting latest timestamp for AA
Traceback (most recent call last):
  File "/Users/dali/workspace/ib_python/runner/services/historical_data_service.py", line 24, in get_latest_timestamp
    response = self.stub.GetLatestTimeStamp(request)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 604, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 506, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1581165879.542047000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3876,"referenced_errors":[{"created":"@1581165877.584632000","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":395,"grpc_status":14}]}"
>
2020-02-08 12:44:39,542 INFO download_runner.impl.historical_runner:32 sending - historical data request : AA 2019-01-01 2020-01-01
2020-02-08 12:44:40,727 INFO download_runner.impl.historical_runner:35 sent - historical data request : AA 2019-01-01 2020-01-01
2020-02-08 12:44:40,727 DEBUG download_runner.impl.historical_runner:36 request accounted for...
2020-02-08 12:44:40,727 INFO download_runner.impl.historical_runner:37 status : True
2020-02-08 12:44:40,727 INFO download_runner.impl.historical_runner:42 Historical data request sent : AA 2019-01-01 2020-01-01
2020-02-08 12:44:40,727 DEBUG download_runner.impl.historical_end_reader:37 poll stock ? => True
2020-02-08 12:44:40,728 ERROR root:30 unhandled exception getting latest timestamp for AAAU
Traceback (most recent call last):
  File "/Users/dali/workspace/ib_python/runner/services/historical_data_service.py", line 24, in get_latest_timestamp
    response = self.stub.GetLatestTimeStamp(request)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 604, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 506, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1581165880.727939000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3876,"referenced_errors":[{"created":"@1581165877.584632000","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":395,"grpc_status":14}]}"
>
2020-02-08 12:44:40,728 INFO download_runner.impl.historical_runner:32 sending - historical data request : AAAU 2019-01-01 2020-01-01
2020-02-08 12:44:41,685 INFO download_runner.impl.historical_runner:35 sent - historical data request : AAAU 2019-01-01 2020-01-01
2020-02-08 12:44:41,686 DEBUG download_runner.impl.historical_runner:36 request accounted for...
2020-02-08 12:44:41,686 INFO download_runner.impl.historical_runner:37 status : True
2020-02-08 12:44:41,686 INFO download_runner.impl.historical_runner:42 Historical data request sent : AAAU 2019-01-01 2020-01-01
2020-02-08 12:44:41,686 DEBUG download_runner.impl.historical_end_reader:37 poll stock ? => True
2020-02-08 12:44:41,686 ERROR root:30 unhandled exception getting latest timestamp for AACG
Traceback (most recent call last):
  File "/Users/dali/workspace/ib_python/runner/services/historical_data_service.py", line 24, in get_latest_timestamp
    response = self.stub.GetLatestTimeStamp(request)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 604, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 506, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1581165881.686435000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3876,"referenced_errors":[{"created":"@1581165877.584632000","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":395,"grpc_status":14}]}"
>
2020-02-08 12:44:41,686 INFO download_runner.impl.historical_runner:32 sending - historical data request : AACG 2019-01-01 2020-01-01
2020-02-08 12:44:42,804 INFO download_runner.impl.historical_runner:35 sent - historical data request : AACG 2019-01-01 2020-01-01
2020-02-08 12:44:42,804 DEBUG download_runner.impl.historical_runner:36 request accounted for...
2020-02-08 12:44:42,804 INFO download_runner.impl.historical_runner:37 status : True
2020-02-08 12:44:42,804 INFO download_runner.impl.historical_runner:42 Historical data request sent : AACG 2019-01-01 2020-01-01
2020-02-08 12:44:42,804 DEBUG download_runner.impl.historical_end_reader:37 poll stock ? => True
2020-02-08 12:44:42,805 ERROR root:30 unhandled exception getting latest timestamp for AADR
Traceback (most recent call last):
  File "/Users/dali/workspace/ib_python/runner/services/historical_data_service.py", line 24, in get_latest_timestamp
    response = self.stub.GetLatestTimeStamp(request)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 604, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 506, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1581165882.804988000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3876,"referenced_errors":[{"created":"@1581165877.584632000","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":395,"grpc_status":14}]}"
>
2020-02-08 12:44:42,805 INFO download_runner.impl.historical_runner:32 sending - historical data request : AADR 2019-01-01 2020-01-01
2020-02-08 12:44:43,784 INFO download_runner.impl.historical_runner:35 sent - historical data request : AADR 2019-01-01 2020-01-01
2020-02-08 12:44:43,784 DEBUG download_runner.impl.historical_runner:36 request accounted for...
2020-02-08 12:44:43,784 INFO download_runner.impl.historical_runner:37 status : True
2020-02-08 12:44:43,784 INFO download_runner.impl.historical_runner:42 Historical data request sent : AADR 2019-01-01 2020-01-01
2020-02-08 12:44:43,784 DEBUG download_runner.impl.historical_end_reader:37 poll stock ? => True
2020-02-08 12:44:43,784 ERROR root:30 unhandled exception getting latest timestamp for AAL
Traceback (most recent call last):
  File "/Users/dali/workspace/ib_python/runner/services/historical_data_service.py", line 24, in get_latest_timestamp
    response = self.stub.GetLatestTimeStamp(request)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 604, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 506, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1581165883.784890000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3876,"referenced_errors":[{"created":"@1581165877.584632000","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":395,"grpc_status":14}]}"
>
2020-02-08 12:44:43,785 INFO download_runner.impl.historical_runner:32 sending - historical data request : AAL 2019-01-01 2020-01-01
2020-02-08 12:44:44,622 INFO download_runner.impl.historical_runner:35 sent - historical data request : AAL 2019-01-01 2020-01-01
2020-02-08 12:44:44,623 DEBUG download_runner.impl.historical_runner:36 request accounted for...
2020-02-08 12:44:44,623 INFO download_runner.impl.historical_runner:37 status : True
2020-02-08 12:44:44,623 INFO download_runner.impl.historical_runner:42 Historical data request sent : AAL 2019-01-01 2020-01-01
2020-02-08 12:44:44,623 DEBUG download_runner.impl.historical_end_reader:37 poll stock ? => True
2020-02-08 12:44:44,624 ERROR root:30 unhandled exception getting latest timestamp for AAMC
Traceback (most recent call last):
  File "/Users/dali/workspace/ib_python/runner/services/historical_data_service.py", line 24, in get_latest_timestamp
    response = self.stub.GetLatestTimeStamp(request)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 604, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 506, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1581165884.624000000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3876,"referenced_errors":[{"created":"@1581165884.623998000","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":395,"grpc_status":14}]}"
>
2020-02-08 12:44:44,625 INFO download_runner.impl.historical_runner:32 sending - historical data request : AAMC 2019-01-01 2020-01-01
2020-02-08 12:44:45,670 INFO download_runner.impl.historical_runner:35 sent - historical data request : AAMC 2019-01-01 2020-01-01
2020-02-08 12:44:45,671 DEBUG download_runner.impl.historical_runner:36 request accounted for...
2020-02-08 12:44:45,671 INFO download_runner.impl.historical_runner:37 status : True
2020-02-08 12:44:45,671 INFO download_runner.impl.historical_runner:42 Historical data request sent : AAMC 2019-01-01 2020-01-01
2020-02-08 12:44:45,671 DEBUG download_runner.impl.historical_end_reader:37 poll stock ? => True
2020-02-08 12:44:45,671 ERROR root:30 unhandled exception getting latest timestamp for AAME
Traceback (most recent call last):
  File "/Users/dali/workspace/ib_python/runner/services/historical_data_service.py", line 24, in get_latest_timestamp
    response = self.stub.GetLatestTimeStamp(request)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 604, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 506, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1581165885.671802000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3876,"referenced_errors":[{"created":"@1581165884.623998000","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":395,"grpc_status":14}]}"
>
2020-02-08 12:44:45,672 INFO download_runner.impl.historical_runner:32 sending - historical data request : AAME 2019-01-01 2020-01-01
2020-02-08 12:44:46,720 INFO download_runner.impl.historical_runner:35 sent - historical data request : AAME 2019-01-01 2020-01-01
2020-02-08 12:44:46,720 DEBUG download_runner.impl.historical_runner:36 request accounted for...
2020-02-08 12:44:46,720 INFO download_runner.impl.historical_runner:37 status : True
2020-02-08 12:44:46,720 INFO download_runner.impl.historical_runner:42 Historical data request sent : AAME 2019-01-01 2020-01-01
2020-02-08 12:44:46,720 DEBUG download_runner.impl.historical_end_reader:37 poll stock ? => True
2020-02-08 12:44:46,721 ERROR root:30 unhandled exception getting latest timestamp for AAN
Traceback (most recent call last):
  File "/Users/dali/workspace/ib_python/runner/services/historical_data_service.py", line 24, in get_latest_timestamp
    response = self.stub.GetLatestTimeStamp(request)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 604, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 506, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1581165886.721210000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3876,"referenced_errors":[{"created":"@1581165884.623998000","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":395,"grpc_status":14}]}"
>
2020-02-08 12:44:46,721 INFO download_runner.impl.historical_runner:32 sending - historical data request : AAN 2019-01-01 2020-01-01
2020-02-08 12:44:48,087 INFO download_runner.impl.historical_runner:35 sent - historical data request : AAN 2019-01-01 2020-01-01
2020-02-08 12:44:48,087 DEBUG download_runner.impl.historical_runner:36 request accounted for...
2020-02-08 12:44:48,087 INFO download_runner.impl.historical_runner:37 status : True
2020-02-08 12:44:48,087 INFO download_runner.impl.historical_runner:42 Historical data request sent : AAN 2019-01-01 2020-01-01
2020-02-08 12:44:48,088 DEBUG download_runner.impl.historical_end_reader:37 poll stock ? => True
2020-02-08 12:44:48,088 ERROR root:30 unhandled exception getting latest timestamp for AAOI
Traceback (most recent call last):
  File "/Users/dali/workspace/ib_python/runner/services/historical_data_service.py", line 24, in get_latest_timestamp
    response = self.stub.GetLatestTimeStamp(request)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 604, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 506, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1581165888.088284000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3876,"referenced_errors":[{"created":"@1581165884.623998000","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":395,"grpc_status":14}]}"
>
2020-02-08 12:44:48,088 INFO download_runner.impl.historical_runner:32 sending - historical data request : AAOI 2019-01-01 2020-01-01
2020-02-08 12:51:50,838 INFO download_runner.impl.historical_runner:35 sent - historical data request : AAOI 2019-01-01 2020-01-01
2020-02-08 12:51:50,838 DEBUG download_runner.impl.historical_runner:36 request accounted for...
2020-02-08 12:51:50,838 INFO download_runner.impl.historical_runner:37 status : True
2020-02-08 12:51:50,838 INFO download_runner.impl.historical_runner:42 Historical data request sent : AAOI 2019-01-01 2020-01-01
2020-02-08 12:51:50,838 DEBUG download_runner.impl.historical_end_reader:37 poll stock ? => True
2020-02-08 12:51:50,839 ERROR root:30 unhandled exception getting latest timestamp for AAON
Traceback (most recent call last):
  File "/Users/dali/workspace/ib_python/runner/services/historical_data_service.py", line 24, in get_latest_timestamp
    response = self.stub.GetLatestTimeStamp(request)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 604, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 506, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1581166310.839020000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3876,"referenced_errors":[{"created":"@1581166292.780254000","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":395,"grpc_status":14}]}"
>
2020-02-08 12:51:50,839 INFO download_runner.impl.historical_runner:32 sending - historical data request : AAON 2019-01-01 2020-01-01
2020-02-08 12:52:24,273 INFO download_runner.impl.historical_runner:35 sent - historical data request : AAON 2019-01-01 2020-01-01
2020-02-08 12:52:24,273 DEBUG download_runner.impl.historical_runner:36 request accounted for...
2020-02-08 12:52:24,273 INFO download_runner.impl.historical_runner:37 status : True
2020-02-08 12:52:24,273 INFO download_runner.impl.historical_runner:42 Historical data request sent : AAON 2019-01-01 2020-01-01
2020-02-08 12:52:24,273 DEBUG download_runner.impl.historical_end_reader:37 poll stock ? => True
2020-02-08 12:52:24,275 ERROR root:30 unhandled exception getting latest timestamp for AAP
Traceback (most recent call last):
  File "/Users/dali/workspace/ib_python/runner/services/historical_data_service.py", line 24, in get_latest_timestamp
    response = self.stub.GetLatestTimeStamp(request)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 604, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 506, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1581166344.275291000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3876,"referenced_errors":[{"created":"@1581166292.780254000","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":395,"grpc_status":14}]}"
>
2020-02-08 12:52:24,277 INFO download_runner.impl.historical_runner:32 sending - historical data request : AAP 2019-01-01 2020-01-01
2020-02-08 12:52:25,605 INFO download_runner.impl.historical_runner:35 sent - historical data request : AAP 2019-01-01 2020-01-01
2020-02-08 12:52:25,605 DEBUG download_runner.impl.historical_runner:36 request accounted for...
2020-02-08 12:52:25,605 INFO download_runner.impl.historical_runner:37 status : True
2020-02-08 12:52:25,605 INFO download_runner.impl.historical_runner:42 Historical data request sent : AAP 2019-01-01 2020-01-01
2020-02-08 12:52:25,605 DEBUG download_runner.impl.historical_end_reader:37 poll stock ? => True
2020-02-08 12:52:25,606 ERROR root:30 unhandled exception getting latest timestamp for AAPL
Traceback (most recent call last):
  File "/Users/dali/workspace/ib_python/runner/services/historical_data_service.py", line 24, in get_latest_timestamp
    response = self.stub.GetLatestTimeStamp(request)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 604, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 506, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1581166345.606510000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3876,"referenced_errors":[{"created":"@1581166292.780254000","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":395,"grpc_status":14}]}"
>
2020-02-08 12:52:25,607 INFO download_runner.impl.historical_runner:32 sending - historical data request : AAPL 2019-01-01 2020-01-01
2020-02-08 12:52:26,808 INFO download_runner.impl.historical_runner:35 sent - historical data request : AAPL 2019-01-01 2020-01-01
2020-02-08 12:52:26,808 DEBUG download_runner.impl.historical_runner:36 request accounted for...
2020-02-08 12:52:26,809 INFO download_runner.impl.historical_runner:37 status : True
2020-02-08 12:52:26,809 INFO download_runner.impl.historical_runner:42 Historical data request sent : AAPL 2019-01-01 2020-01-01
2020-02-08 12:52:26,809 DEBUG download_runner.impl.historical_end_reader:37 poll stock ? => True
2020-02-08 12:52:26,809 ERROR root:30 unhandled exception getting latest timestamp for AAT
Traceback (most recent call last):
  File "/Users/dali/workspace/ib_python/runner/services/historical_data_service.py", line 24, in get_latest_timestamp
    response = self.stub.GetLatestTimeStamp(request)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 604, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 506, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1581166346.809391000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3876,"referenced_errors":[{"created":"@1581166292.780254000","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":395,"grpc_status":14}]}"
>
2020-02-08 12:52:26,809 INFO download_runner.impl.historical_runner:32 sending - historical data request : AAT 2019-01-01 2020-01-01
2020-02-08 12:52:28,025 INFO download_runner.impl.historical_runner:35 sent - historical data request : AAT 2019-01-01 2020-01-01
2020-02-08 12:52:28,025 DEBUG download_runner.impl.historical_runner:36 request accounted for...
2020-02-08 12:52:28,026 INFO download_runner.impl.historical_runner:37 status : True
2020-02-08 12:52:28,026 INFO download_runner.impl.historical_runner:42 Historical data request sent : AAT 2019-01-01 2020-01-01
2020-02-08 12:52:28,026 DEBUG download_runner.impl.historical_end_reader:37 poll stock ? => True
2020-02-08 12:52:28,028 ERROR root:30 unhandled exception getting latest timestamp for AAU
Traceback (most recent call last):
  File "/Users/dali/workspace/ib_python/runner/services/historical_data_service.py", line 24, in get_latest_timestamp
    response = self.stub.GetLatestTimeStamp(request)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 604, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 506, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1581166348.027482000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3876,"referenced_errors":[{"created":"@1581166292.780254000","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":395,"grpc_status":14}]}"
>
2020-02-08 12:52:28,029 INFO download_runner.impl.historical_runner:32 sending - historical data request : AAU 2019-01-01 2020-01-01
2020-02-08 12:52:29,104 INFO download_runner.impl.historical_runner:35 sent - historical data request : AAU 2019-01-01 2020-01-01
2020-02-08 12:52:29,105 DEBUG download_runner.impl.historical_runner:36 request accounted for...
2020-02-08 12:52:29,105 INFO download_runner.impl.historical_runner:37 status : True
2020-02-08 12:52:29,105 INFO download_runner.impl.historical_runner:42 Historical data request sent : AAU 2019-01-01 2020-01-01
2020-02-08 12:52:29,105 DEBUG download_runner.impl.historical_end_reader:37 poll stock ? => True
2020-02-08 12:52:29,106 ERROR root:30 unhandled exception getting latest timestamp for AAWW
Traceback (most recent call last):
  File "/Users/dali/workspace/ib_python/runner/services/historical_data_service.py", line 24, in get_latest_timestamp
    response = self.stub.GetLatestTimeStamp(request)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 604, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 506, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1581166349.106004000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3876,"referenced_errors":[{"created":"@1581166292.780254000","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":395,"grpc_status":14}]}"
>
2020-02-08 12:52:29,106 INFO download_runner.impl.historical_runner:32 sending - historical data request : AAWW 2019-01-01 2020-01-01
2020-02-08 12:52:30,298 INFO download_runner.impl.historical_runner:35 sent - historical data request : AAWW 2019-01-01 2020-01-01
2020-02-08 12:52:30,298 DEBUG download_runner.impl.historical_runner:36 request accounted for...
2020-02-08 12:52:30,298 INFO download_runner.impl.historical_runner:37 status : True
2020-02-08 12:52:30,298 INFO download_runner.impl.historical_runner:42 Historical data request sent : AAWW 2019-01-01 2020-01-01
2020-02-08 12:52:30,298 DEBUG download_runner.impl.historical_end_reader:37 poll stock ? => True
2020-02-08 12:52:30,299 ERROR root:30 unhandled exception getting latest timestamp for AAXJ
Traceback (most recent call last):
  File "/Users/dali/workspace/ib_python/runner/services/historical_data_service.py", line 24, in get_latest_timestamp
    response = self.stub.GetLatestTimeStamp(request)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 604, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 506, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1581166350.299147000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3876,"referenced_errors":[{"created":"@1581166292.780254000","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":395,"grpc_status":14}]}"
>
2020-02-08 12:52:30,299 INFO download_runner.impl.historical_runner:32 sending - historical data request : AAXJ 2019-01-01 2020-01-01
2020-02-08 12:52:31,536 INFO download_runner.impl.historical_runner:35 sent - historical data request : AAXJ 2019-01-01 2020-01-01
2020-02-08 12:52:31,536 DEBUG download_runner.impl.historical_runner:36 request accounted for...
2020-02-08 12:52:31,536 INFO download_runner.impl.historical_runner:37 status : True
2020-02-08 12:52:31,536 INFO download_runner.impl.historical_runner:42 Historical data request sent : AAXJ 2019-01-01 2020-01-01
2020-02-08 12:52:31,536 DEBUG download_runner.impl.historical_end_reader:37 poll stock ? => True
2020-02-08 12:52:31,536 ERROR root:30 unhandled exception getting latest timestamp for AAXN
Traceback (most recent call last):
  File "/Users/dali/workspace/ib_python/runner/services/historical_data_service.py", line 24, in get_latest_timestamp
    response = self.stub.GetLatestTimeStamp(request)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 604, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 506, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1581166351.536754000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3876,"referenced_errors":[{"created":"@1581166292.780254000","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":395,"grpc_status":14}]}"
>
2020-02-08 12:52:31,537 INFO download_runner.impl.historical_runner:32 sending - historical data request : AAXN 2019-01-01 2020-01-01
2020-02-08 12:52:32,565 INFO download_runner.impl.historical_runner:35 sent - historical data request : AAXN 2019-01-01 2020-01-01
2020-02-08 12:52:32,566 DEBUG download_runner.impl.historical_runner:36 request accounted for...
2020-02-08 12:52:32,566 INFO download_runner.impl.historical_runner:37 status : True
2020-02-08 12:52:32,566 INFO download_runner.impl.historical_runner:42 Historical data request sent : AAXN 2019-01-01 2020-01-01
2020-02-08 12:52:32,566 DEBUG download_runner.impl.historical_end_reader:37 poll stock ? => True
2020-02-08 12:52:32,567 ERROR root:30 unhandled exception getting latest timestamp for AB
Traceback (most recent call last):
  File "/Users/dali/workspace/ib_python/runner/services/historical_data_service.py", line 24, in get_latest_timestamp
    response = self.stub.GetLatestTimeStamp(request)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 604, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 506, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1581166352.567034000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3876,"referenced_errors":[{"created":"@1581166292.780254000","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":395,"grpc_status":14}]}"
>
2020-02-08 12:52:32,567 INFO download_runner.impl.historical_runner:32 sending - historical data request : AB 2019-01-01 2020-01-01
2020-02-08 12:52:33,644 INFO download_runner.impl.historical_runner:35 sent - historical data request : AB 2019-01-01 2020-01-01
2020-02-08 12:52:33,644 DEBUG download_runner.impl.historical_runner:36 request accounted for...
2020-02-08 12:52:33,645 INFO download_runner.impl.historical_runner:37 status : True
2020-02-08 12:52:33,645 INFO download_runner.impl.historical_runner:42 Historical data request sent : AB 2019-01-01 2020-01-01
2020-02-08 12:52:33,645 DEBUG download_runner.impl.historical_end_reader:37 poll stock ? => True
2020-02-08 12:52:33,646 ERROR root:30 unhandled exception getting latest timestamp for ABB
Traceback (most recent call last):
  File "/Users/dali/workspace/ib_python/runner/services/historical_data_service.py", line 24, in get_latest_timestamp
    response = self.stub.GetLatestTimeStamp(request)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 604, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 506, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1581166353.646534000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3876,"referenced_errors":[{"created":"@1581166292.780254000","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":395,"grpc_status":14}]}"
>
2020-02-08 12:52:33,647 INFO download_runner.impl.historical_runner:32 sending - historical data request : ABB 2019-01-01 2020-01-01
2020-02-08 12:52:34,548 INFO download_runner.impl.historical_runner:35 sent - historical data request : ABB 2019-01-01 2020-01-01
2020-02-08 12:52:34,549 DEBUG download_runner.impl.historical_runner:36 request accounted for...
2020-02-08 12:52:34,549 INFO download_runner.impl.historical_runner:37 status : True
2020-02-08 12:52:34,549 INFO download_runner.impl.historical_runner:42 Historical data request sent : ABB 2019-01-01 2020-01-01
2020-02-08 12:52:34,549 DEBUG download_runner.impl.historical_end_reader:37 poll stock ? => True
2020-02-08 12:52:34,550 ERROR root:30 unhandled exception getting latest timestamp for ABBV
Traceback (most recent call last):
  File "/Users/dali/workspace/ib_python/runner/services/historical_data_service.py", line 24, in get_latest_timestamp
    response = self.stub.GetLatestTimeStamp(request)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 604, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/dali/workspace/ib_python/runner/venv/lib/python3.7/site-packages/grpc/_channel.py", line 506, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1581166354.550332000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3876,"referenced_errors":[{"created":"@1581166292.780254000","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":395,"grpc_status":14}]}"
>
2020-02-08 12:52:34,552 INFO download_runner.impl.historical_runner:32 sending - historical data request : ABBV 2019-01-01 2020-01-01
